### ISSUE TITLE
扫描完结果上报异常，method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jkl1994** [Tencent/CodeAnalysis#102]
2022-01-14 18:40:19,175-INFO-util.logutil: results written to /opt/app/CodeAnalysis/client/data/taskdirs/task_60/scc_result_5e320b12752611ec9eb60492265d2584.json
2022-01-14 18:40:19,189-INFO-util.logutil: Task_60 (CheckStyle) starts ...
2022-01-14 18:40:29,299-INFO-util.logutil: Task_60 is done.
2022-01-14 18:40:29,345-ERROR-util.wrapper: method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)
2022-01-14 18:40:29,345-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
2022-01-14 18:40:34,353-ERROR-util.wrapper: method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)
2022-01-14 18:40:34,354-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
2022-01-14 18:40:39,362-ERROR-util.wrapper: method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)
2022-01-14 18:40:39,363-WARNING-util.wrapper: method(upload_file) call still fails after 2 retries
2022-01-14 18:40:39,363-INFO-util.logutil: 
****************************************************************************************************
代码分析结果: 
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
****************************************************************************************************
2022-01-14 18:40:39,363-INFO-util.logutil: json report: /opt/app/CodeAnalysis/client/scan_status.json
2022-01-14 18:40:39,364-ERROR-util.logutil: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/app/CodeAnalysis/client/node/localrunner.py", line 396, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "/opt/app/CodeAnalysis/client/node/localtask/runlocaltask.py", line 96, in scan_project
    self._proj_id).run()
  File "/opt/app/CodeAnalysis/client/node/localtask/runtask.py", line 170, in run
    ResultCheck.upload_task_result(task, self._proj_id)
  File "/opt/app/CodeAnalysis/client/node/localtask/runtask.py", line 97, in upload_task_result
    data_url, log_url = TaskRunner.upload_result_detail(proj_id, task.task_id, task_dir, data, task.task_log)
  File "node/taskrunner.py", line 59, in node.taskrunner.TaskRunner.upload_result_detail
  File "util/wrapper.py", line 51, in util.wrapper._RetryMethod.__call__
  File "util/wrapper.py", line 107, in util.wrapper.Retry.__retry_call
  File "util/wrapper.py", line 92, in util.wrapper.Retry.__retry_call
  File "/opt/app/CodeAnalysis/client/util/api/fileserver.py", line 103, in upload_file
    return self.__upload_data(fp, rel_url, headers)
  File "/opt/app/CodeAnalysis/client/util/api/fileserver.py", line 87, in __upload_data
    HttpClient(self._server_url, rel_url, headers=headers, data=data, proxies=self._proxies).put()
  File "/opt/app/CodeAnalysis/client/util/api/httpclient.py", line 82, in put
    result = HttpRequest.request(url=self.url, headers=self.headers, body=self.data, method="PUT")
  File "/opt/app/CodeAnalysis/client/util/api/httpclient.py", line 45, in request
    dict_result = json.loads(str_result)
  File "/usr/local/python3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/python3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
You have new mail in /var/spool/mail/root

**Comment by Lingghh** [comment]
客户端配置FILE_SERVER的token跟当前codedog.ini的token是否一致呢？

**Comment by jkl1994** [comment]
拉取的最新版代码重新部署的，token配置是一致的；
![image](https://user-images.githubusercontent.com/34265722/149688746-6d374714-f8f0-4357-855e-b967f5221743.png)
![image](https://user-images.githubusercontent.com/34265722/149688789-88322d6b-29fb-442b-a6cb-b046f116820b.png)
![image](https://user-images.githubusercontent.com/34265722/149688804-ff47257f-68b4-4dd4-b8db-fbd55ecd4331.png)

**Comment by jkl1994** [comment]
修改了 config.ini里的配置后，可以上报

**Comment by ZyjacyaD** [comment]
修改了啥解决的？

**Comment by jkl1994** [comment]
> 修改了啥解决的？

![image](https://user-images.githubusercontent.com/34265722/149717164-58654eab-08ee-4965-9815-f4007884cd20.png)
改了下server的地址，用了80端口的那个；用8000端口的就报错
