### ISSUE TITLE
安卓代码在git仓库src时下执行androidlint失败

### ISSUE THREAD

**Issue by nlhm** [Tencent/CodeAnalysis#1047]
![微信图片_20240403171152](https://github.com/Tencent/CodeAnalysis/assets/46469364/6ffc92bd-11ab-471a-a80a-50c03caa0812)
---
---

安卓程序的源码、gradle放置在git仓库src目录下，在上图中代码目录填写src后执行分析。
执行分析失败，提示编译不通过。在分析方案中的编译编译命令中输入cd src，编译成功，jaff等需要编译的规则分析可以通过。但是在执行androidlint时失败。日志见下

---
> 2024-03-22 17:40:27,864-INFO: start to run task: AndroidLint, execute_processes: ['compile', 'analyze', 'datahandle']
2024-03-22 17:40:27,936-INFO: Load tool config: https://git.code.tencent.com/TCA/tca-tools/puppy-tools-config.git
2024-03-22 17:40:29,792-INFO: Initing common tools ...
2024-03-22 17:40:29,792-INFO: Initing 3 tools, please wait a minute ...
[Tools init]:   0%|                                                           | 0/3 [00:00<?, ?it/s]
[Tools init]:  33%|█████████████████                                  | 1/3 [00:01<00:03,  1.56s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.88it/s]
2024-03-22 17:40:31,398-INFO: Initialize tools done.(use time: 1.61s)
2024-03-22 17:40:31,402-INFO: run cmd: git lfs install
2024-03-22 17:40:31,444-INFO: Git LFS initialized.
2024-03-22 17:40:31,613-INFO: Initing other tools ...
2024-03-22 17:40:31,640-INFO: Initing 2 tools, please wait a minute ...
[Tools init]:   0%|                                                           | 0/2 [00:00<?, ?it/s]
[Tools init]:  50%|█████████████████████████▌                         | 1/2 [00:01<00:01,  1.42s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.39it/s]
2024-03-22 17:40:33,081-INFO: Initialize tools done.(use time: 1.44s)
2024-03-22 17:40:33,090-INFO: task start : <class 'task.model.compile.CompileTask'>
2024-03-22 17:40:33,090-INFO: pre_compile start.
2024-03-22 17:40:33,090-INFO: start __checkout_source_dir.
2024-03-22 17:40:33,090-INFO: 常规项目，直接拉取或复用本地缓存资源.
2024-03-22 17:40:34,844-INFO: load_source_dir done. source_dir insert env. sourcedir: /home/rino/Rino/CodeAnalysis/client/data/sourcedirs/git_0xp2nvqy
2024-03-22 17:40:34,852-INFO: pre_compile done.
2024-03-22 17:40:34,857-INFO: PATH =
\****************************************************************************************************
/home/rino/Rino/CodeAnalysis/tools/linux-jdk1.8.0_65/bin
/home/rino/Rino/CodeAnalysis/tools/linux-git-lfs-v3.1.2
/home/rino/Rino/CodeAnalysis/tools/linux-git-lfs-v3.1.2
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/snap/bin
/usr/lib/jvm/java-8-openjdk-amd64/bin
/opt/gradle-6.5/bin
\****************************************************************************************************
2024-03-22 17:40:34,858-INFO: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
2024-03-22 17:40:34,859-INFO: Codelint only scans main code.
2024-03-22 17:40:34,921-INFO: Cmd:
cd src && gradle compileDebugSources --no-daemon -Dorg.gradle.jvmargs=-Xmx1536m
export BUILD_CWD=src
2024-03-22 17:40:34,921-INFO: Generated shell file: /home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617/workdir/tca_build.sh
2024-03-22 17:40:34,922-INFO: basic compile start.
2024-03-22 17:40:34,922-INFO: subprocc normal mode: ['bash', '/home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617/workdir/tca_build.sh']
2024-03-22 17:40:34,922-INFO: run build cmd: bash /home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617/workdir/tca_build.sh
2024-03-22 17:40:34,923-INFO: task params taskdir: /home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617
2024-03-22 17:40:35,233-INFO: [文件数]过滤前：3002，过滤后：2635
2024-03-22 17:40:35,234-INFO: ['/home/rino/Rino/CodeAnalysis/tools/linux-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617/scc_result_3bad1e9ae83011eeb0dc07349ccca98b.json', '/home/rino/Rino/CodeAnalysis/client/data/sourcedirs/git_0xp2nvqy']
2024-03-22 17:40:35,475-INFO: results written to /home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617/scc_result_3bad1e9ae83011eeb0dc07349ccca98b.json
2024-03-22 17:40:35,788-INFO: To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.5/userguide/gradle_daemon.html.
2024-03-22 17:40:35,921-INFO: 上报代码行数: {'code_line_num': 337208, 'comment_line_num': 60667, 'blank_line_num': 44635, 'total_line_num': 442510, 'filtered_code_line_num': 240128, 'filtered_comment_line_num': 36369, 'filtered_blank_line_num': 28066, 'filtered_total_line_num': 304563, 'filtered_lang_count': {'Kotlin': {'file_num': 54, 'code_line_num': 3070, 'comment_line_num': 2816, 'blank_line_num': 895, 'total_line_num': 6781}, 'CMake': {'file_num': 10, 'code_line_num': 245, 'comment_line_num': 193, 'blank_line_num': 125, 'total_line_num': 563}, 'Properties File': {'file_num': 2, 'code_line_num': 11, 'comment_line_num': 16, 'blank_line_num': 0, 'total_line_num': 27}, 'C': {'file_num': 13, 'code_line_num': 2481, 'comment_line_num': 671, 'blank_line_num': 502, 'total_line_num': 3654}, 'Android Interface Definition Language': {'file_num': 3, 'code_line_num': 32, 'comment_line_num': 6, 'blank_line_num': 5, 'total_line_num': 43}, 'JSON': {'file_num': 2, 'code_line_num': 19, 'comment_line_num': 0, 'blank_line_num': 0, 'total_line_num': 19}, 'CSV': {'file_num': 1, 'code_line_num': 58, 'comment_line_num': 0, 'blank_line_num': 0, 'total_line_num': 58}, 'Plain Text': {'file_num': 2, 'code_line_num': 17, 'comment_line_num': 0, 'blank_line_num': 2, 'total_line_num': 19}, 'Gradle': {'file_num': 12, 'code_line_num': 422, 'comment_line_num': 46, 'blank_line_num': 81, 'total_line_num': 549}, 'Batch': {'file_num': 1, 'code_line_num': 66, 'comment_line_num': 0, 'blank_line_num': 24, 'total_line_num': 90}, 'C Header': {'file_num': 197, 'code_line_num': 25337, 'comment_line_num': 15750, 'blank_line_num': 5518, 'total_line_num': 46605}, 'gitignore': {'file_num': 10, 'code_line_num': 59, 'comment_line_num': 28, 'blank_line_num': 17, 'total_line_num': 104}, 'XML': {'file_num': 434, 'code_line_num': 93230, 'comment_line_num': 423, 'blank_line_num': 6908, 'total_line_num': 100561}, 'Java': {'file_num': 380, 'code_line_num': 76776, 'comment_line_num': 9466, 'blank_line_num': 9266, 'total_line_num': 95508}, 'Prolog': {'file_num': 9, 'code_line_num': 141, 'comment_line_num': 0, 'blank_line_num': 23, 'total_line_num': 164}, 'C++': {'file_num': 91, 'code_line_num': 38062, 'comment_line_num': 6913, 'blank_line_num': 4669, 'total_line_num': 49644}, 'Autoconf': {'file_num': 1, 'code_line_num': 0, 'comment_line_num': 5, 'blank_line_num': 2, 'total_line_num': 7}, 'C++ Header': {'file_num': 1, 'code_line_num': 102, 'comment_line_num': 36, 'blank_line_num': 29, 'total_line_num': 167}}}
2024-03-22 17:40:36,882-INFO: Daemon will be stopped at the end of the build stopping after processing
2024-03-22 17:40:44,484-INFO: 
2024-03-22 17:40:44,485-INFO: > Configure project :app
...
...
...
...
...
2024-03-22 17:41:00,569-INFO: BUILD SUCCESSFUL in 25s
2024-03-22 17:41:00,569-INFO: 103 actionable tasks: 12 executed, 91 up-to-date
2024-03-22 17:41:00,927-INFO: exist_error_flag : False
2024-03-22 17:41:00,928-INFO: exist_success_flag : True
2024-03-22 17:41:00,928-INFO: exist_100_flag : False
2024-03-22 17:41:00,928-INFO: cov_no_file_emitted : False
2024-03-22 17:41:00,928-INFO: 编译成功！
2024-03-22 17:41:00,928-INFO: basic compile done.
2024-03-22 17:41:00,929-INFO: done_compile start.
2024-03-22 17:41:00,929-INFO: task done : <class 'task.model.compile.CompileTask'>
2024-03-22 17:41:00,930-INFO: task start : <class 'task.model.analyze.AnalyzeTask'>
2024-03-22 17:41:00,930-INFO: pre_analyze start.
2024-03-22 17:41:00,930-INFO: pre_analyze done.
2024-03-22 17:41:00,985-INFO: subprocc : ['gradle', 'lint']
2024-03-22 17:41:01,868-INFO: 
2024-03-22 17:41:01,869-INFO: FAILURE: Build failed with an exception.
2024-03-22 17:41:01,869-INFO: 
2024-03-22 17:41:01,869-INFO: * What went wrong:
2024-03-22 17:41:01,869-INFO: Task 'lint' not found in root project 'git_0xp2nvqy'. Some candidates are: 'init'.
2024-03-22 17:41:01,869-INFO: 
2024-03-22 17:41:01,869-INFO: * Try:
2024-03-22 17:41:01,870-INFO: Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
2024-03-22 17:41:01,870-INFO: 
2024-03-22 17:41:01,870-INFO: * Get more help at https://help.gradle.org
2024-03-22 17:41:01,870-INFO: 
2024-03-22 17:41:01,870-INFO: BUILD FAILED in 754ms
2024-03-22 17:41:01,880-WARNING: task status code is 211
2024-03-22 17:41:01,880-WARNING: task messsage: AnalyzeTaskError: Error[211]: lint执行失败，请查看日志排查原因
2024-03-22 17:41:01,881-WARNING: task result: 
Traceback (most recent call last):
  File "task/puppytask.py", line 63, in run
    response = TaskRunner(self._request_file, self._response_file).run_task()
  File "task/runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "/home/rino/Rino/CodeAnalysis/client/task/taskmgr.py", line 73, in taskrunner
    result = task.runner(params)
  File "/home/rino/Rino/CodeAnalysis/client/task/model/analyze.py", line 49, in runner
    return self.tool.analyze(params)
  File "/home/rino/Rino/CodeAnalysis/client/tool/androidlint.py", line 81, in analyze
    return self.gradle_mode_analyze(params)
  File "/home/rino/Rino/CodeAnalysis/client/tool/androidlint.py", line 160, in gradle_mode_analyze
    raise AnalyzeTaskError("lint执行失败，请查看日志排查原因")
util.exceptions.AnalyzeTaskError: Error[211]: lint执行失败，请查看日志排查原因
2024-03-22 17:41:01,882-INFO: task result: /home/rino/Rino/CodeAnalysis/client/data/taskdirs/task_617/task_response.json

---
日志中提到了`Task 'lint' not found in root project 'git_0xp2nvqy'. Some candidates are: 'init'.` ,类似的提示在前面提到的编译不成功时也有出现，当时是通过cd src解决的。
是不是在执行androidlint时，指令是在仓库根目录下执行而不是在src下执行？因为我之前有个测试项目代码直接在仓库根目录时lint是可以分析并成功的。
TCA版本是github 的最新release版本。

**Comment by cyw3** [comment]
可以设置 环境变量 BUILD_CWD 指定编译执行的目录位置，需要是相对于代码库根目录的相对路径

https://github.com/Tencent/CodeAnalysis/blob/872c21c2c43f4245a27dc526948ba32e1b5b9f3a/client/tool/androidlint.py#L140C37-L140C46

**Comment by nlhm** [comment]
> 可以设置 环境变量 BUILD_CWD 指定编译执行的目录位置，需要是相对于代码库根目录的相对路径
> 
已解决。
