### ISSUE TITLE
扫描失败，提示SCM鉴权失败 账号密码错误

### ISSUE THREAD

**Issue by uniquewdl** [Tencent/CodeAnalysis#1057]

**Comment by Lingghh** [comment]
可以检查下 scmproxy 服务的日志输出，确认下错误原因
参考链接：[faq](https://tencent.github.io/CodeAnalysis/zh/quickStarted/FAQ.html#server%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95)

**Comment by uniquewdl** [comment]
> 可以检查下 scmproxy 服务的日志输出，确认下错误原因 参考链接：[faq](https://tencent.github.io/CodeAnalysis/zh/quickStarted/FAQ.html#server%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E4%B8%8E%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95)

2024-04-22 10:37:26,724 PID:1 apis.py-line:119 | INFO - method: latest_revision, scm_url: git@gitlab.xxxx.com:xxx/xx#master, scm_type: ssh+git, username: None
2024-04-22 10:37:26,725 PID:1 apis.py-line:72 | INFO - start to checkout or update: /var/www/django/codedog/sourcedirs/8743971f98269f534e0f2fb975cae36ab424433d
2024-04-22 10:37:26,826 PID:1 proxyserver.py-line:79 | ERROR - Error info:
Traceback (most recent call last):
  File "proxyserver.py", line 74, in _dispatch
    response = func(*params)
  File "/var/www/django/codedog/apis.py", line 125, in wrapper
    coding_project_id=scm_info.get("coding_project_id"))
  File "/var/www/django/codedog/apis.py", line 105, in __get_client_by_scm_type
    self.__checkout_sourdir(scm_client, source_dir)
  File "/var/www/django/codedog/apis.py", line 82, in __checkout_sourdir
    scm_client.checkout(enable_submodules=False, enable_lfs=False)
  File "src/_cmdgit.py", line 1585, in src._cmdgit.CmdGit.checkout
  File "src/_cmdgit.py", line 1426, in src._cmdgit.CmdGit._clone
  File "src/_cmdgit.py", line 224, in src._cmdgit.CmdGit._cmd_error_check
lib._scmbase.ScmCommandError: fatal: Could not read from remote repository.
2024-04-22 10:37:26,826 PID:1 utils.py-line:49 | INFO - handle git err msg: fatal: Could not read from remote repository.
2024-04-22 10:37:26,826 PID:1 proxyserver.py-line:82 | ERROR - {method: latest_revision, error_message: fatal: Could not read from remote repository.}
