### ISSUE TITLE
"NodeError: Error[204]: 当前环境不支持cobra工具步骤:['analyze']

### ISSUE THREAD

**Issue by jkl1994** [Tencent/CodeAnalysis#106]
代码分析结果: 
NodeError: Error[204]: 当前环境不支持cobra工具步骤:['analyze'].
****************************************************************************************************
2022-01-17 14:39:31,148-INFO-util.logutil: json report: /opt/app/CodeAnalysis/client/scan_status.json
2022-01-17 14:39:31,148-ERROR-util.logutil: NodeError: Error[204]: 当前环境不支持cobra工具步骤:['analyze'].
Traceback (most recent call last):
  File "/opt/app/CodeAnalysis/client/node/localrunner.py", line 384, in run
    request_generator.generate_request(proj_conf)
  File "/opt/app/CodeAnalysis/client/node/localtask/requestgenerator.py", line 153, in generate_request
    execute_request_list = self._get_execute_request_list(job_context, task_list)
  File "/opt/app/CodeAnalysis/client/node/localtask/requestgenerator.py", line 183, in _get_execute_request_list
    raise NodeError(code=errcode.E_NODE_TASK_CONFIG, msg=f"当前环境不支持{task_name}工具步骤:{remote_procs}.")
util.exceptions.NodeError: Error[204]: 当前环境不支持cobra工具步骤:['analyze'].

**Comment by jkl1994** [comment]
单独启动cobra执行扫描是没有问题的，但是通过 python3 codepuppy.py localscan执行就报错；pip相关依赖已经安装；请问具体报错在哪看

**Comment by cyw3** [comment]
可以参考 #86 

更新下CodeAnalysis代码库，执行./compose_init.sh，然后重试下

**Comment by jkl1994** [comment]
把linux本地python命令指向python3，问题解决
