### ISSUE TITLE
乌班图部署client报错

### ISSUE THREAD

**Issue by x364574152** [Tencent/CodeAnalysis#1066]
乌班图部署报错，系统版本为22.04 amd64位。
Python导包错误

# docker run -it --rm  -v $PWD:/workspace/client -v $SOURCE_DIR:/workspace/src  --name tca-client tca-client
Traceback (most recent call last):
  File "codepuppy.py", line 22, in <module>
    from node.toolloader.loadtool import ToolLoader, ToolConfigLoader
  File "/workspace/client/node/toolloader/loadtool.py", line 19, in <module>
    from node.toolloader.gitload import GitLoader
  File "/workspace/client/node/toolloader/gitload.py", line 16, in <module>
    from util.cmdscm import ScmClient
  File "/workspace/client/util/cmdscm.py", line 20, in <module>
    from ._cmdsvn import CmdSvn
ImportError: /workspace/client/util/_cmdsvn.cpython-37m-x86_64-linux-gnu.so: invalid ELF header

**Comment by cyw3** [comment]
麻烦切换成 centos7.9或者tencentos2 试试
