### ISSUE TITLE
windows 当前环境不支持cobra工具步骤:['analyze']

### ISSUE THREAD

**Issue by Grapefruit-Shu** [Tencent/CodeAnalysis#109]
****************************************************************************************************
2022-01-18 11:06:19,942-INFO-util.logutil: json report: H:/CodeAnalysis-main/client/scan_status.json
2022-01-18 11:06:19,942-ERROR-util.logutil: NodeError: Error[204]: 当前环境不支持cobra工具步骤:['analyze'].
Traceback (most recent call last):
  File "H:\CodeAnalysis-main\client\node\localrunner.py", line 380, in run
    request_generator.generate_request(proj_conf)
  File "H:\CodeAnalysis-main\client\node\localtask\requestgenerator.py", line 153, in generate_request
    execute_request_list = self._get_execute_request_list(job_context, task_list)
  File "H:\CodeAnalysis-main\client\node\localtask\requestgenerator.py", line 183, in _get_execute_request_list
    raise NodeError(code=errcode.E_NODE_TASK_CONFIG, msg=f"当前环境不支持{task_name}工具步骤:{remote_procs}.")
util.exceptions.NodeError: Error[204]: 当前环境不支持cobra工具步骤:['analyze'].
***************************************************************************************************

subprocc_stderr.log  报错：python: can't open file 'cobra.py': [Errno 2] No such file or directory

**Comment by cyw3** [comment]
这里Cobra不支持在windows下执行。目前新版已经设置不默认执行cobra。
麻烦更新下CodeAnalysis代码库，执行./compose_init.sh，然后重试下

可以参考 #86

**Comment by Grapefruit-Shu** [comment]
好的
