### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Akityo** [Tencent/CodeAnalysis#11]
`➜  client git:(main) ✗ python3 codepuppy.py localscan
Traceback (most recent call last):
  File "/Users/xxxxx/tools/CodeAnalysis/client/codepuppy.py", line 18, in <module>
    from util.gitconfig import GitConfig
  File "/Users/xxxxx/tools/CodeAnalysis/client/util/gitconfig.py", line 10, in <module>
    from util.subprocc import SubProcController
ModuleNotFoundError: No module named 'util.subprocc'
➜  client git:(main) ✗ pwd
/Users/xxxxx/tools/CodeAnalysis/client`

按照教程安装了pip3 install -r client/requirements/app_reqs.pip
也执行了
进入到client/requirements目录
在命令行中执行安装脚本install.sh(linux/mac环境)或install.bat(windows环境)

**Comment by Lingghh** [comment]
这里是用什么python版本运行呢？
代码运行需要依赖python3.7版本

**Comment by Akityo** [comment]
额，docker关了之后，重启，compose-up -d

其中codeanalysis_main-beat_1 起不来


[2022-01-04 11:28:53,132: INFO/MainProcess] beat: Starting...
-2022-01-04 11:28:53,132-INFO-celery.beat: beat: Starting...
[2022-01-04 11:28:53,155: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:28:53,155-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 11:33:53,254: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:33:53,254-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 11:38:53,344: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:38:53,344-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 11:43:53,423: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:43:53,423-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 11:48:53,500: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:48:53,500-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 11:53:53,598: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:53:53,598-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 11:58:53,690: INFO/MainProcess] Loading 0 tasks
-2022-01-04 11:58:53,690-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:03:53,788: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:03:53,788-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:08:53,867: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:08:53,867-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:13:53,944: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:13:53,944-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:18:54,028: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:18:54,028-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:23:54,108: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:23:54,108-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:28:54,204: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:28:54,204-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:33:54,304: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:33:54,304-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:38:54,406: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:38:54,406-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:43:54,492: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:43:54,492-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:48:54,582: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:48:54,582-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:53:54,678: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:53:54,678-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 12:58:54,761: INFO/MainProcess] Loading 0 tasks
-2022-01-04 12:58:54,761-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:03:54,853: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:03:54,853-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:08:54,950: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:08:54,950-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:13:55,045: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:13:55,045-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:18:55,140: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:18:55,140-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:23:55,241: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:23:55,241-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:28:55,322: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:28:55,322-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:33:55,421: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:33:55,421-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:38:55,522: INFO/MainProcess] Loading 0 tasks
celery beat v4.3.0 (rhubarb) is starting.
celery beat v4.3.0 (rhubarb) is starting.
celery beat v4.3.0 (rhubarb) is starting.
celery beat v4.3.0 (rhubarb) is starting.
celery beat v4.3.0 (rhubarb) is starting.
celery beat v4.3.0 (rhubarb) is starting.
-2022-01-04 13:38:55,522-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:43:55,617: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:43:55,617-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:48:55,706: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:48:55,706-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:53:55,780: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:53:55,780-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 13:58:55,871: INFO/MainProcess] Loading 0 tasks
-2022-01-04 13:58:55,871-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:03:55,944: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:03:55,944-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:08:56,034: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:08:56,034-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:13:56,120: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:13:56,120-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:18:56,220: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:18:56,220-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:23:56,238: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:23:56,238-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:28:56,334: INFO/MainProcess] Loading 1 tasks
-2022-01-04 14:28:56,334-INFO-redbeat.schedulers: Loading 1 tasks
[2022-01-04 14:28:56,341: INFO/MainProcess] Scheduler: Sending due task check-project-active (apps.codeproj.tasks.base.check_project_active)
-2022-01-04 14:28:56,341-INFO-redbeat.schedulers: Scheduler: Sending due task check-project-active (apps.codeproj.tasks.base.check_project_active)
[2022-01-04 14:30:00,064: INFO/MainProcess] Loading 1 tasks
-2022-01-04 14:30:00,064-INFO-redbeat.schedulers: Loading 1 tasks
[2022-01-04 14:30:00,065: INFO/MainProcess] Scheduler: Sending due task check-project-active (apps.codeproj.tasks.base.check_project_active)
-2022-01-04 14:30:00,065-INFO-redbeat.schedulers: Scheduler: Sending due task check-project-active (apps.codeproj.tasks.base.check_project_active)
[2022-01-04 14:35:00,161: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:35:00,161-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:40:00,222: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:40:00,222-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:45:00,314: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:45:00,314-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:50:00,397: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:50:00,397-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 14:55:00,469: INFO/MainProcess] Loading 0 tasks
-2022-01-04 14:55:00,469-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:00:00,567: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:00:00,567-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:05:00,637: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:05:00,637-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:10:00,738: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:10:00,738-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:15:00,838: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:15:00,838-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:20:00,931: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:20:00,931-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:25:01,031: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:25:01,031-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:30:01,128: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:30:01,128-INFO-redbeat.schedulers: Loading 0 tasks
[2022-01-04 15:35:01,229: INFO/MainProcess] Loading 0 tasks
-2022-01-04 15:35:01,229-INFO-redbeat.schedulers: Loading 0 tasks
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
ERROR: Pidfile (celerybeat.pid) already exists.
Seems we're already running? (pid: 1)
celery beat v4.3.0 (rhubarb) is starting.

**Comment by cocorunning** [comment]
代码运行需要依赖python3.7版本

**Comment by Lingghh** [comment]
这里可以在项目根目录下执行以下命令试试
``` 
docker-compose rm -s main-beat
docker-compose up -d main-beat
```

**Comment by Akityo** [comment]
Traceback (most recent call last):
  File "/CodeAnalysis/client/node/localrunner.py", line 374, in run
    request_generator.generate_request(proj_conf)
  File "/CodeAnalysis/client/node/localtask/requestgenerator.py", line 145, in generate_request
    ToolLoader(tool_names=local_task_names, task_list=task_list).git_load_tools(print_enable=False)
  File "/CodeAnalysis/client/node/loadtool.py", line 164, in git_load_tools
    LoadToolProcess().run(load_tool_list)
  File "/CodeAnalysis/client/node/loadtool.py", line 104, in run
    self.__load_tool(tool_info)
  File "/CodeAnalysis/client/node/loadtool.py", line 91, in __load_tool
    scm_auth_info=tool_info.get("auth_info"))
  File "/CodeAnalysis/client/node/loadtool.py", line 76, in load_tool
    GitLoader(scm_url=git_url, dest_dir=tool_dirpath, scm_auth_info=scm_auth_info, print_enable=False).load()
  File "/CodeAnalysis/client/node/gitload.py", line 132, in load
    raise NodeError(code=E_NODE_TASK_SCM_FAILED, msg=str(err))
util.exceptions.NodeError: Error[203]: fatal: unable to access 'https://github.com/TCATools/linux-scc.git/': Failed to connect to github.com port 443: Connection refused


emm，能不能改改方案，有些网络环境下，比较蛋疼

**Comment by Akityo** [comment]
@Lingghh 或者提供个参数可以配置github proxy或者啥的

**Comment by Lingghh** [comment]
感谢反馈，这里我们评估看看
