### ISSUE TITLE
执行phthon3相关指令提示：No module named 'util._cmdsvn'

### ISSUE THREAD

**Issue by YuriTam** [Tencent/CodeAnalysis#1114]
Traceback (most recent call last):
  File "/home/lighthouse/CodeAnalysis/client/codepuppy.py", line 22, in <module>
    from node.toolloader.loadtool import ToolLoader, ToolConfigLoader
  File "/home/lighthouse/CodeAnalysis/client/node/toolloader/loadtool.py", line 19, in <module>
    from node.toolloader.gitload import GitLoader
  File "/home/lighthouse/CodeAnalysis/client/node/toolloader/gitload.py", line 16, in <module>
    from util.cmdscm import ScmClient
  File "/home/lighthouse/CodeAnalysis/client/util/cmdscm.py", line 20, in <module>
    from ._cmdsvn import CmdSvn
ModuleNotFoundError: No module named 'util._cmdsvn'

**Comment by cyw3** [comment]
1. 请问是什么部署方式呢？

2. 这是在用源码接入client节点吗？
可以试试先执行以下命令安装必要的库
```bash
bash ./scripts/base/install_bin.sh
```

**Comment by hwangyungping** [comment]
client容器部署方式也遇到相同的问题

**Comment by cyw3** [comment]
> client容器部署方式也遇到相同的问题

有没有执行该命令呢？

**Comment by hwangyungping** [comment]
> > client容器部署方式也遇到相同的问题
> 
> 有没有执行该命令呢？

执行命令对应的操作，因为我是在内部网络没法直接访问github。我是手动下载，相当于手动download_lib然后deepmove。
难道手动download_lib的git仓库版本不对？

**Comment by cyw3** [comment]
可以进到client位置查看 util/_cmdgit.cpython-37m-x86_64-linux-gnu.so 文件是否存在。

**Comment by hwangyungping** [comment]
client/util下so文件存在的，这些文件是从tca_LIB中深度拷贝的，我看日志deepmove是操作了的。所以我怀疑是不是我手动download tca_lib是不是版本不兼容？

**Comment by cyw3** [comment]
ls -al client/util/

看看

**Comment by LingYoung0320** [comment]
> 1. 请问是什么部署方式呢？
> 2. 这是在用源码接入client节点吗？
>    可以试试先执行以下命令安装必要的库
> 
> bash ./scripts/base/install_bin.sh
还是报错，缺少util._cmdsvn
