### ISSUE TITLE
代码库登记报与账号不匹配,scm_log报ScmCommandError

### ISSUE THREAD

**Issue by NostarLee** [Tencent/CodeAnalysis#114]
![image](https://user-images.githubusercontent.com/98004773/150063701-1f889482-d078-4b7b-9e95-bf58b28f95f5.png)
![image](https://user-images.githubusercontent.com/98004773/150063755-4361ac16-88cc-4cc6-8df1-e9d274ae7669.png)

Traceback (most recent call last):
  File "proxyserver.py", line 74, in _dispatch
    response = func(*params)
  File "/data1/htdocs/CodeAnalysis-main/server/projects/scmproxy/apis.py", line 115, in wrapper
    return func(*func_args, **kwargs)
  File "/data1/htdocs/CodeAnalysis-main/server/projects/scmproxy/apis.py", line 151, in auth_check
    scm_client.check_auth(raise_exception=True)
  File "src/_cmdgit.py", line 691, in src._cmdgit.CmdGit.check_auth
  File "src/_cmdgit.py", line 686, in src._cmdgit.CmdGit.check_auth
  File "src/_cmdgit.py", line 224, in src._cmdgit.CmdGit._cmd_error_check
lib._scmbase.ScmCommandError: usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...

debug找到代码，构造scm_client
scm_client = CmdGit(_parmes)
执行checkout能执行一段时间后报错，查看路径实际把主仓库代码已经拉下来了且切到了master分支，但trace看起来在子模块拉取时
![image](https://user-images.githubusercontent.com/98004773/150063935-06b73677-8a96-42f3-adad-c25b4086ded8.png)出错了（仓库无子仓库）
同样的，执行check_auth，抛出与页面登记代码库同样的错
scm_client.check_auth(raise_exception=True)
ScmAuthError: usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/_cmdgit.py", line 691, in src._cmdgit.CmdGit.check_auth
  File "src/_cmdgit.py", line 686, in src._cmdgit.CmdGit.check_auth
  File "src/_cmdgit.py", line 224, in src._cmdgit.CmdGit._cmd_error_check
lib._scmbase.ScmCommandError: usage: git ls-remote [--heads] [--tags]  [-u <exec> | --upload-pack <exec>] <repository> <refs>...

_cmdgit.cpython-37m-x86_64-linux-gnu.so与服务器的git版本有关吗？无法进一步debug查到原因跑起来，请求协助

**Comment by Lingghh** [comment]
本地是使用什么git版本呢？

**Comment by NostarLee** [comment]
> 
git version 1.7.1

**Comment by Lingghh** [comment]
这里需要麻烦升级一下git版本哈

**Comment by NostarLee** [comment]
![image](https://user-images.githubusercontent.com/98004773/150082915-31c4bf38-acf0-4410-86cc-30465dc61052.png)


> 这里需要麻烦升级一下git版本哈

![image](https://user-images.githubusercontent.com/98004773/150082934-b4467516-a826-4321-8dbb-0b7cf71813fc.png)
解决了，确实是git version问题，感谢
另外建议在README.md中能更新一些问题列表，说明这种细节问题。Centos自带和源里的git版本都挺低的~

**Comment by Lingghh** [comment]
感谢反馈，我们补充一下
