### ISSUE TITLE
svn登记代码仓库使用http协议地址在添加代码分支进行扫描任务后，系统默认将svn仓库地址配置为https协议，无法进行扫描任务执行

### ISSUE THREAD

**Issue by icytnt** [Tencent/CodeAnalysis#1176]
仓库登记
![lQLPJxhvWkseCK_NAovNBS2wQjbBztA9C-kGwLg-TCi3AA_1325_651](https://github.com/user-attachments/assets/0db94feb-080f-42d4-a413-cbdd16419ce5)
添加代码分支报错
![b2a22cee98bb9aff96e0884d653248d](https://github.com/user-attachments/assets/b0bc11f0-40ec-4707-95ea-dc64a648265f)
日志记录内容
![731876be877996bc7c7f5d7870d2b14](https://github.com/user-attachments/assets/4a75b1ae-140d-4a48-9532-81249adbd2ce)

麻烦看一下是什么原因

**Comment by nickcdon** [comment]
<img width="854" alt="image" src="https://github.com/user-attachments/assets/268d2da5-48e5-48c9-bac2-12248d58866a">

**Comment by nickcdon** [comment]
可以看下文档是否可以解决：https://tencent.github.io/CodeAnalysis/zh/quickStarted/FAQ.html#_3-3-2-%E4%BB%A3%E7%A0%81%E5%BA%93%E7%99%BB%E8%AE%B0%E6%88%90%E5%8A%9F%E5%90%8E-%E5%BC%80%E5%90%AF%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BB%A3%E7%A0%81%E5%88%86%E6%9E%90%E6%97%B6-%E5%87%BA%E7%8E%B0%E4%BB%A3%E7%A0%81%E5%BA%93%E5%8F%8A%E8%B4%A6%E5%8F%B7%E4%B8%8D%E5%8C%B9%E9%85%8D

**Comment by yaoliwei** [comment]
我的问题和这个类似，不过多了一个问题：svn服务器的端口号看上去被tca服务器忽略了。
我们的svn地址是这样的： http://10.20.180.221:3690/repo/Software/PublicShare/Projects/01_dentalProject/02_Code
端口号是3690，并且不支持https。

log是这样的：
tomo@scmdata:/mnt/data/CodeAnalysis/.docker_temp$ tail -30  ./logs/servers/scmproxy/server_stderr.log
svn: E000111: Error running context: Connection refused}
127.0.0.1 - - [15/Oct/2024 10:41:03] "POST /RPC2 HTTP/1.1" 200 -
2024-10-15 10:52:50,879 PID:479 apis.py-line:119 | INFO - method: auth_check, scm_url: http://10.20.180.221:3690/repo/Software/PublicShare/Projects/01_dentalProject, scm_type: svn, username: yaoliwei
2024-10-15 10:52:50,880 PID:479 apis.py-line:70 | INFO - no need to checkout
2024-10-15 10:52:50,906 PID:479 threading.py-line:870 | WARNING - ignore warning/error: svn: warning: cannot set LC_CTYPE locale
2024-10-15 10:52:50,907 PID:479 threading.py-line:870 | WARNING - ignore warning/error: svn: warning: environment variable LC_ALL is en_US.UTF-8
2024-10-15 10:52:50,908 PID:479 threading.py-line:870 | WARNING - ignore warning/error: svn: warning: please check that your locale name is correct
127.0.0.1 - - [15/Oct/2024 10:52:50] "POST /RPC2 HTTP/1.1" 200 -
2024-10-15 10:56:48,098 PID:479 apis.py-line:119 | INFO - method: branch_check, scm_url: https://10.20.180.221/repo/Software/PublicShare/Projects/01_dentalProject/02_Code, scm_type: svn, username: yaoliwei
2024-10-15 10:56:48,099 PID:479 apis.py-line:70 | INFO - no need to checkout
2024-10-15 10:56:48,126 PID:479 threading.py-line:870 | WARNING - ignore warning/error: svn: warning: cannot set LC_CTYPE locale
2024-10-15 10:56:48,127 PID:479 threading.py-line:870 | WARNING - ignore warning/error: svn: warning: environment variable LC_ALL is en_US.UTF-8
2024-10-15 10:56:48,127 PID:479 threading.py-line:870 | WARNING - ignore warning/error: svn: warning: please check that your locale name is correct
2024-10-15 10:56:48,201 PID:479 proxyserver.py-line:79 | ERROR - Error info:
Traceback (most recent call last):
  File "proxyserver.py", line 74, in _dispatch
    response = func(*params)
  File "/CodeAnalysis/server/projects/scmproxy/apis.py", line 128, in wrapper
    return func(*func_args, **kwargs)
  File "/CodeAnalysis/server/projects/scmproxy/apis.py", line 176, in branch_check
    scm_client.info_by_remote()
  File "src/_cmdsvn.py", line 300, in src._cmdsvn.CmdSvn.info_by_remote
  File "src/_cmdsvn.py", line 241, in src._cmdsvn.CmdSvn._base_info
  File "src/_cmdsvn.py", line 163, in src._cmdsvn.CmdSvn._cmd_error_check
lib._scmbase.ScmCommandError: svn: E170013: Unable to connect to a repository at URL 'https://10.20.180.221/repo/Software/PublicShare/Projects/01_dentalProject/02_Code'
svn: E000111: Error running context: Connection refused
2024-10-15 10:56:48,202 PID:479 utils.py-line:81 | INFO - handle svn git err msg: svn: E170013: Unable to connect to a repository at URL 'https://10.20.180.221/repo/Software/PublicShare/Projects/01_dentalProject/02_Code'
svn: E000111: Error running context: Connection refused
2024-10-15 10:56:48,202 PID:479 proxyserver.py-line:82 | ERROR - {method: branch_check, error_message: svn: E170013: Unable to connect to a repository at URL 'https://10.20.180.221/repo/Software/PublicShare/Projects/01_dentalProject/02_Code'
svn: E000111: Error running context: Connection refused}
tomo@scmdata:/mnt/data/CodeAnalysis/.docker_temp$

**Comment by yaoliwei** [comment]
http/https issue has been resolved after adjustment of the flag HTTPS_CLONE_FLAG, thoug the port issue still there. 
Pls help.
