### ISSUE TITLE
扫描失败 找不到每一步产生的 task_response.json

### ISSUE THREAD

**Issue by Akitata** [Tencent/CodeAnalysis#118]
Java + gradle项目，扫描时会在scc, pmd, findbus等步骤报错 提示

```
FileNotFoundError: [Errno 2] No such file or directory: '/CodeAnalysis/client/data/taskdirs/task_65_1/task_response.json'
****************************************************************************************************
2022-01-19 20:52:26,837-INFO-util.logutil: json report: /CodeAnalysis/client/scan_status.json
2022-01-19 20:52:26,837-ERROR-util.logutil: FileNotFoundError: [Errno 2] No such file or directory: '/CodeAnalysis/client/data/taskdirs/task_65_1/task_response.json'
Traceback (most recent call last):
  File "/CodeAnalysis/client/node/localrunner.py", line 396, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "/CodeAnalysis/client/node/localtask/runlocaltask.py", line 96, in scan_project
    self._proj_id).run()
  File "/CodeAnalysis/client/node/localtask/runtask.py", line 173, in run
    log_url, data_url)
  File "/CodeAnalysis/client/node/localtask/runtask.py", line 46, in get_task_result
    with open(task.response_file, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/CodeAnalysis/client/data/taskdirs/task_65_1/task_response.json'
```

看其他issues提示findbugs组件需要配置编译命令，我在UI上配置编译命令后下载方案，配置文件里面没有添加到相关配置。

在配置文件里手动配置编译命令以后，报错依旧存在

麻烦各位帮忙看一下，谢谢！

**Comment by Lingghh** [comment]
这段报错日志上面的其他日志麻烦也提供一下哈

**Comment by Akitata** [comment]
@Lingghh hello,这里是初始化工具完成后打印的全部日志

```
2022-01-20 20:00:29,039-INFO-util.logutil: Initialize tools done.(use time: 6.34s)
2022-01-20 20:00:29,162-INFO-util.logutil: Start to count code lines...
2022-01-20 20:00:29,165-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
2022-01-20 20:00:29,165-INFO-util.logutil: Codelint only cans main code.
2022-01-20 20:00:29,194-INFO-util.logutil: [文件数]过滤前：40，过滤后：40
2022-01-20 20:00:29,197-INFO-util.logutil: ['/CodeAnalysis-main/client/data/tools/mac-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/CodeAnalysis-main/client/data/taskdirs/task_88/scc_result_8fb4381079e811ec8d0f8c8590b760ad.json', '/code/project']
2022-01-20 20:00:29,249-INFO-util.logutil: results written to /CodeAnalysis-main/client/data/taskdirs/task_88/scc_result_8fb4381079e811ec8d0f8c8590b760ad.json
2022-01-20 20:00:29,288-INFO-util.logutil: Task_88 (GoMetaLinter) starts ...
2022-01-20 20:00:39,399-INFO-util.logutil: Task_88 is done.
2022-01-20 20:00:40,012-INFO-util.logutil:
****************************************************************************************************
代码分析结果:
FileNotFoundError: [Errno 2] No such file or directory: '/CodeAnalysis-main/client/data/taskdirs/task_88_1/task_response.json'
****************************************************************************************************
2022-01-20 20:00:40,012-INFO-util.logutil: json report: /CodeAnalysis-main/client/scan_status.json
2022-01-20 20:00:40,013-ERROR-util.logutil: FileNotFoundError: [Errno 2] No such file or directory: '/CodeAnalysis-main/client/data/taskdirs/task_88_1/task_response.json'
Traceback (most recent call last):
  File "/CodeAnalysis-main/client/node/localrunner.py", line 396, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "/CodeAnalysis-main/client/node/localtask/runlocaltask.py", line 96, in scan_project
    self._proj_id).run()
  File "/CodeAnalysis-main/client/node/localtask/runtask.py", line 173, in run
    log_url, data_url)
  File "/CodeAnalysis-main/client/node/localtask/runtask.py", line 46, in get_task_result
    with open(task.response_file, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/CodeAnalysis-main/client/data/taskdirs/task_88_1/task_response.json'
```

此外，taskdirs目录下生成了这些文件
```
.
├── task_88
│   ├── codeline_data.json 
│   └── scc_result_8fb4381079e811ec8d0f8c8590b760ad.json
└── task_88_1
    ├── task.log
    ├── task_request.json
    └── workdir
```

其中task_88里的codeline_data.json和scc_result_8fb4381079e811ec8d0f8c8590b760ad.json及task_request.json看起来是正常数据

task.log内容为：

```
Traceback (most recent call last):
  File "task/puppytask.py", line 22, in <module>
    from task.runtask import TaskRunner
ModuleNotFoundError: No module named 'task.runtask'
```

**Comment by Lingghh** [comment]
好的，我们这边分析看一下

**Comment by bensonhome** [comment]
@Akitata 请问当前运行机器是什么操作系统？

**Comment by Akitata** [comment]
@bensonhome MacBook Pro，10.14.6系统

Python 3.7.8rc1 (v3.7.8rc1:5f3933d61d, Jun 17 2020, 04:59:23)
[Clang 6.0 (clang-600.0.57)] on darwin

**Comment by bensonhome** [comment]
@Akitata 请问是apple M1芯片还是Intel芯片的呢？

**Comment by Akitata** [comment]
@bensonhome inter

**Comment by bensonhome** [comment]
@Akitata 看起来是兼容的，麻烦确认下代码库是完整的吗，下面这个文件存在吗：
CodeAnalysis/client/task/runtask.cpython-37m-darwin.so

**Comment by Akitata** [comment]
@Akitata 是有的。而且我试了下同一份代码，在Linux上能成功运行，mac不行

**Comment by bensonhome** [comment]
@Akitata 那还是环境兼容问题。这里可以先在linux上运行。
另外我们也提供了docker的方式使用client，在不兼容的mac机器上可以用docker跑，可以参考文档操作：
https://github.com/Tencent/CodeAnalysis/tree/main/client#readme
