### ISSUE TITLE
执行 Tool compile start. 后报错

### ISSUE THREAD

**Issue by Grapefruit-Shu** [Tencent/CodeAnalysis#127]
报错信息如下：
-------------------------------------------------------------------------------------------
2022-01-20 13:16:33,350-INFO-util.logutil: 
****************************************************************************************************
代码分析结果: 
KeyError: 'tool_name'
****************************************************************************************************
2022-01-20 13:16:33,350-INFO-util.logutil: json report: /home/CodeAnalysis-main/client/scan_status.json
2022-01-20 13:16:33,351-ERROR-util.logutil: KeyError: 'tool_name'
Traceback (most recent call last):
  File "/home/CodeAnalysis-main/client/node/localrunner.py", line 384, in run
    request_generator.generate_request(proj_conf)
  File "/home/CodeAnalysis-main/client/node/localtask/requestgenerator.py", line 153, in generate_request
    execute_request_list = self._get_execute_request_list(job_context, task_list)
  File "/home/CodeAnalysis-main/client/node/localtask/requestgenerator.py", line 180, in _get_execute_request_list
    task_name, task_params)
  File "/home/CodeAnalysis-main/client/node/localtask/taskprocessmgr.py", line 65, in get_supported_processes
    supported_processes = TaskMgr.check_tool_usable(task_name, task_params)
  File "/home/CodeAnalysis-main/client/task/taskmgr.py", line 118, in check_tool_usable
    tool_usable_set = tool.check_tool_usable(tool_params)
  File "/home/CodeAnalysis-main/client/tool/cobra.py", line 138, in check_tool_usable
    ToolEnvSet.auto_set_py_env(params=tool_params, version=3)
  File "/home/CodeAnalysis-main/client/tool/util/toolenvset.py", line 115, in auto_set_py_env
    cls.set_py_env(params, version)
  File "/home/CodeAnalysis-main/client/tool/util/toolenvset.py", line 119, in set_py_env
    tool_name = params["tool_name"]
KeyError: 'tool_name'
^CException ignored in: <module 'threading' from '/usr/local/python3/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 1273, in _shutdown
    t.join()
  File "/usr/local/python3/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/local/python3/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
----------------------------------------------------------------------------------------------

**Comment by cyw3** [comment]
感谢反馈。这里已经修复。可以更新下CodeAnalysis代码库，然后重试下

#134

**Comment by Grapefruit-Shu** [comment]
好的
