### ISSUE TITLE
UnicodeEncodeError: 'latin-1'

### ISSUE THREAD

**Issue by D0n9** [Tencent/CodeAnalysis#151]
2022-01-28 16:40:59,591-INFO-util.logutil: Task_86 (CheckStyle) starts ...
2022-01-28 16:40:59,627-INFO-util.logutil: results written to /Users/test/github.com/Tencent/CodeAnalysis/client/data/taskdirs/task_86/scc_result_048c24da801611ec9807acde48001122.json
2022-01-28 16:41:09,707-INFO-util.logutil: Task_86 is done.
2022-01-28 16:41:09,800-ERROR-util.wrapper: method(upload_file) call fails on error: 'latin-1' codec can't encode characters in position 10-11: ordinal not in range(256)
2022-01-28 16:41:09,800-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
2022-01-28 16:41:14,806-ERROR-util.wrapper: method(upload_file) call fails on error: 'latin-1' codec can't encode characters in position 10-11: ordinal not in range(256)
2022-01-28 16:41:14,806-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
2022-01-28 16:41:19,813-ERROR-util.wrapper: method(upload_file) call fails on error: 'latin-1' codec can't encode characters in position 10-11: ordinal not in range(256)
2022-01-28 16:41:19,813-WARNING-util.wrapper: method(upload_file) call still fails after 2 retries
2022-01-28 16:41:19,814-INFO-util.logutil:
****************************************************************************************************
代码分析结果:
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-11: ordinal not in range(256)
****************************************************************************************************
2022-01-28 16:41:19,815-INFO-util.logutil: json report: /Users/test/github.com/Tencent/CodeAnalysis/client/scan_status.json
2022-01-28 16:41:19,815-ERROR-util.logutil: UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-11: ordinal not in range(256)
Traceback (most recent call last):
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/node/localrunner.py", line 396, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/node/localtask/runlocaltask.py", line 96, in scan_project
    self._proj_id).run()
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/node/localtask/runtask.py", line 170, in run
    ResultCheck.upload_task_result(task, self._proj_id)
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/node/localtask/runtask.py", line 97, in upload_task_result
    data_url, log_url = TaskRunner.upload_result_detail(proj_id, task.task_id, task_dir, data, task.task_log)
  File "node/taskrunner.py", line 59, in node.taskrunner.TaskRunner.upload_result_detail
  File "util/wrapper.py", line 51, in util.wrapper._RetryMethod.__call__
  File "util/wrapper.py", line 107, in util.wrapper.Retry.__retry_call
  File "util/wrapper.py", line 92, in util.wrapper.Retry.__retry_call
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/util/api/fileserver.py", line 104, in upload_file
    return self.__upload_data(fp, rel_url, headers)
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/util/api/fileserver.py", line 88, in __upload_data
    HttpClient(self._server_url, rel_url, headers=headers, data=data, proxies=self._proxies).put()
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/util/api/httpclient.py", line 82, in put
    result = HttpRequest.request(url=self.url, headers=self.headers, body=self.data, method="PUT")
  File "/Users/test/github.com/Tencent/CodeAnalysis/client/util/api/httpclient.py", line 43, in request
    response = urlopen(req).read()
  File "/Users/test/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/test/miniconda3/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/test/miniconda3/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Users/test/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/test/miniconda3/lib/python3.7/urllib/request.py", line 1345, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/test/miniconda3/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/test/miniconda3/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/test/miniconda3/lib/python3.7/http/client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "/Users/test/miniconda3/lib/python3.7/http/client.py", line 1202, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-11: ordinal not in range(256)

**Comment by Lingghh** [comment]
可以试试在启动client之前设置一下环境变量
```
export PYTHONIOENCODING=utf-8
```

**Comment by D0n9** [comment]
> 可以试试在启动client之前设置一下环境变量
> 
> ```
> export PYTHONIOENCODING=utf-8
> ```

试过了，还是不行。。

docker 起的

**Comment by Lingghh** [comment]
@D0n9 client是docker启动的吗？

**Comment by D0n9** [comment]
> @D0n9 client是docker启动的吗？

client 不是，用了 virtualenv

**Comment by Lingghh** [comment]
进入virtualenv环境后先执行一下
```
export PYTHONIOENCODING=utf-8
```
再启动client试试

**Comment by D0n9** [comment]
> 

就是这样做的 。。

**Comment by bensonhome** [comment]
@D0n9 麻烦看下virtualenv里面默认编码是什么呢，执行locale查看下？
修改默认编码为en_US.UTF-8试试:
export  LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

**Comment by Lingghh** [comment]
@D0n9 这里看起来是客户端在请求头部中包含了非ascii码，这里方便发一下client的config.ini文件么？

**Comment by D0n9** [comment]
已解决

与编码无关，是 config.ini 文件配置错误导致的。

**Comment by D0n9** [comment]
> @D0n9 这里看起来是客户端在请求头部中包含了非ascii码，这里方便发一下client的config.ini文件么？

没错。。检查了下确实 config.ini 配置的不对

**Comment by Lingghh** [comment]
辛苦了

**Comment by zhicrus** [comment]
我也发生了相似的问题，但是并没用发现config.ini有配置不对的地方，请问你们是怎么解决的呢？我这边只能将分析方案中的html检查给关掉才能正常运行。
我的报错是：
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence

**Comment by Lingghh** [comment]
@zhicrus 麻烦提供一下报错相关的日志

**Comment by ocjdhs** [comment]
@Lingghh 
-2022-02-14 11:00:13,085-INFO-util.logutil: start to run task: HtmlCs, execute_processes: ['analyze', 'datahandle']
-2022-02-14 11:00:13,126-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: pre_analyze start.
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: __checkout_source_dir done. source_dir insert env. sourcedir: D:\CodeRelease
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: pre_analyze done.
-2022-02-14 11:00:13,126-INFO-util.logutil:PATH =
****************************************************************************************************
D:\Software\CodeAnalysis-main\client\data/tools\win-node-v12.16.3/bin
D:\Software\CodeAnalysis-main\client\data\tools\win-node-v12.16.3
... ...(其他路径省略)
****************************************************************************************************
-2022-02-14 11:00:13,126-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-02-14 11:00:13,126-INFO-util.logutil: Codelint only cans main code.
-2022-02-14 11:00:13,188-INFO-util.logutil: [文件数]过滤前：355，过滤后：305
-2022-02-14 11:00:13,188-INFO-util.logutil: 待扫描文件数是: 305
-2022-02-14 11:00:13,188-INFO-util.logutil: 命令行长度限制：8000
-2022-02-14 11:00:13,188-INFO-util.logutil: scan_cmd: htmlcs hint --config D:\Software\CodeAnalysis-main\client\data\taskdirs\task_437\workdir\.htmlcsrc cms-master/web/WEB-INF/cms_admin/advertising_space/list.html  ...（其他文件省略）
-2022-02-14 11:00:14,336-WARNING-task.puppytask: task status code is 201
-2022-02-14 11:00:14,336-WARNING-task.puppytask: task messsage: UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence
-2022-02-14 11:00:14,336-INFO-task.puppytask: task result: D:\Software\CodeAnalysis-main\client\data\taskdirs\task_437\task_response.json

task_response.json中的内容是：

{
 "task_version": "3.0",
 "status": 201,
 "message": "UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence",
 "result": "Traceback (most recent call last):\n  File \"task/puppytask.py\", line 64, in run\n    response = TaskRunner(self._request_file, self._response_file).run_task()\n  File \"task\\runtask.py\", line 63, in task.runtask.TaskRunner.run_task\n  File \"D:\\Software\\CodeAnalysis-main\\client\\task\\taskmgr.py\", line 73, in taskrunner\n    result = task.runner(params)\n  File \"D:\\Software\\CodeAnalysis-main\\client\\task\\model\\analyze.py\", line 49, in runner\n    return self.tool.analyze(params)\n  File \"D:\\Software\\CodeAnalysis-main\\client\\tool\\htmlcs.py\", line 91, in analyze\n    for error in error_file:\nUnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence\n",
 "files": null,
 "start_time": "2022-02-14 11:00:13",
 "end_time": "2022-02-14 11:00:14",
 "time_format": "%Y-%m-%d %H:%M:%S"
}

**Comment by zhicrus** [comment]
@Lingghh 
这是我的报错相关日志，很抱歉昨天登录同伴的账号忘记切回自己的就回复了。我再重新发一下，麻烦了
-2022-02-14 11:00:13,085-INFO-util.logutil: start to run task: HtmlCs, execute_processes: ['analyze', 'datahandle']
-2022-02-14 11:00:13,126-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: pre_analyze start.
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: __checkout_source_dir done. source_dir insert env. sourcedir: D:\CodeRelease
-2022-02-14 11:00:13,126-INFO-task.sourcemgr: pre_analyze done.
-2022-02-14 11:00:13,126-INFO-util.logutil:PATH =

D:\Software\CodeAnalysis-main\client\data/tools\win-node-v12.16.3/bin
D:\Software\CodeAnalysis-main\client\data\tools\win-node-v12.16.3
... ...(其他路径省略)

-2022-02-14 11:00:13,126-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-02-14 11:00:13,126-INFO-util.logutil: Codelint only cans main code.
-2022-02-14 11:00:13,188-INFO-util.logutil: [文件数]过滤前：355，过滤后：305
-2022-02-14 11:00:13,188-INFO-util.logutil: 待扫描文件数是: 305
-2022-02-14 11:00:13,188-INFO-util.logutil: 命令行长度限制：8000
-2022-02-14 11:00:13,188-INFO-util.logutil: scan_cmd: htmlcs hint --config D:\Software\CodeAnalysis-main\client\data\taskdirs\task_437\workdir.htmlcsrc cms-master/web/WEB-INF/cms_admin/advertising_space/list.html ...（其他文件省略）
-2022-02-14 11:00:14,336-WARNING-task.puppytask: task status code is 201
-2022-02-14 11:00:14,336-WARNING-task.puppytask: task messsage: UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence
-2022-02-14 11:00:14,336-INFO-task.puppytask: task result: D:\Software\CodeAnalysis-main\client\data\taskdirs\task_437\task_response.json

task_response.json中的内容是：

{
"task_version": "3.0",
"status": 201,
"message": "UnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence",
"result": "Traceback (most recent call last):\n File "task/puppytask.py", line 64, in run\n response = TaskRunner(self._request_file, self._response_file).run_task()\n File "task\runtask.py", line 63, in task.runtask.TaskRunner.run_task\n File "D:\Software\CodeAnalysis-main\client\task\taskmgr.py", line 73, in taskrunner\n result = task.runner(params)\n File "D:\Software\CodeAnalysis-main\client\task\model\analyze.py", line 49, in runner\n return self.tool.analyze(params)\n File "D:\Software\CodeAnalysis-main\client\tool\htmlcs.py", line 91, in analyze\n for error in error_file:\nUnicodeDecodeError: 'gbk' codec can't decode byte 0xb5 in position 6631: illegal multibyte sequence\n",
"files": null,
"start_time": "2022-02-14 11:00:13",
"end_time": "2022-02-14 11:00:14",
"time_format": "%Y-%m-%d %H:%M:%S"
}

**Comment by Lingghh** [comment]
我们分析一下

**Comment by cyw3** [comment]
@zhicrus 

感谢反馈，已修复。麻烦更新下代码库，重试下。

也欢迎commit共建哈

**Comment by zhicrus** [comment]
@cyw3 
感谢，已成功运行，麻烦你们了
