### ISSUE TITLE
codepuppy localscan raise Error:  No module named 'util.subprocc'

### ISSUE THREAD

**Issue by Anemone95** [Tencent/CodeAnalysis#17]
```bash
root@iZj6c2l4nh4l1ykl9h4r99Z:~/CodeAnalysis/client# python3 codepuppy.py localscan
Traceback (most recent call last):
  File "codepuppy.py", line 18, in <module>
    from util.gitconfig import GitConfig
  File "/root/CodeAnalysis/client/util/gitconfig.py", line 10, in <module>
    from util.subprocc import SubProcController
ModuleNotFoundError: No module named 'util.subprocc'
root@iZj6c2l4nh4l1ykl9h4r99Z:~/CodeAnalysis/client# python3 --version
Python 3.8.10
```

**Comment by Lingghh** [comment]
目前依赖python 3.7版本运行，可以切换为python3.7版本试试

**Comment by Anemone95** [comment]
切换了依然报错：
```bash
root@fad5964aaa23:/CodeAnalysis/client# python3 codepuppy.py localscan
Traceback (most recent call last):
  File "codepuppy.py", line 18, in <module>
    from util.gitconfig import GitConfig
  File "/CodeAnalysis/client/util/gitconfig.py", line 10, in <module>
    from util.subprocc import SubProcController
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
root@fad5964aaa23:/CodeAnalysis/client# python3 --version
Python 3.7.12
```

**Comment by Lingghh** [comment]
这里的报错是python动态库找不到
可以在``/usr``目录下找一下libpython3.7m.so.1.0：可以执行一下以下命令：
```
$ find / -name libpython3.7m.so.1.0
# /xx/xx需要替换为实际路径
$ ln -s /xx/xx/libpython3.7m.so.1.0 /usr/lib/libpython3.7m.so.1.0
$ ldconfig
```

**Comment by color-way** [comment]
链接libpython3.7m.so.1.0后报错：
Traceback (most recent call last):
  File "codepuppy.py", line 18, in <module>
    from util.gitconfig import GitConfig
  File "/home/test/CodeAnalysis/client/util/gitconfig.py", line 10, in <module>
    from util.subprocc import SubProcController
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /lib/libpython3.7m.so.1.0)

**Comment by Lingghh** [comment]
@color-way 这里看起来是本地安装的glibc版本较低导致运行失败，可以升级一下glibc再重新跑一下试试
