### ISSUE TITLE
Error[226]: 第三方工具执行异常,未生成结果文件: /client/data/tools/rips-scanner/result.json

### ISSUE THREAD

**Issue by T3st0r-Git** [Tencent/CodeAnalysis#178]
```
root@test:/home/test/桌面/code/CodeAnalysis_client# cat client/data/taskdirs/task_520/task.log 
-2022-03-11 14:38:48,438-INFO-util.logutil: start to run task: Rips开源版, execute_processes: ['analyze', 'datahandle']
-2022-03-11 14:38:48,563-WARNING-task.taskmgr: 不是内置工具,使用自定义工具模块(No module named 'tool.rips')
-2022-03-11 14:38:48,566-INFO-task.taskmgr: task start : <class 'task.model.analyze.AnalyzeTask'>
-2022-03-11 14:38:48,567-INFO-task.sourcemgr: pre_analyze start.
-2022-03-11 14:38:48,567-INFO-task.sourcemgr: start __checkout_source_dir.
-2022-03-11 14:38:48,567-INFO-task.sourcemgr: __checkout_source_dir done. source_dir insert env. sourcedir: /client/will_check_codes/wujiang_xb
-2022-03-11 14:38:48,567-INFO-task.sourcemgr: pre_analyze done.
-2022-03-11 14:38:48,567-INFO-util.logutil: PATH =
****************************************************************************************************
/usr/local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
****************************************************************************************************
-2022-03-11 14:38:48,567-INFO-util.logutil: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
-2022-03-11 14:38:48,568-INFO-util.logutil: Codelint only cans main code.
-2022-03-11 14:38:48,693-INFO-util.logutil: USE_LOCAL_TOOL=True, use local tool dir: /client/data/tools/rips-scanner
-2022-03-11 14:38:48,694-INFO-util.logutil: Use local tool dir: /client/data/tools/rips-scanner
-2022-03-11 14:38:48,712-INFO-util.logutil: 获取需要扫描的文件
-2022-03-11 14:38:48,791-INFO-task.basic.common: /bin/sh: 1: php: not found
-2022-03-11 14:38:48,820-INFO-util.logutil: use SubProcController run cmd: php main.php
-2022-03-11 14:38:48,871-WARNING-task.puppytask: task status code is 226
-2022-03-11 14:38:48,872-WARNING-task.puppytask: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /client/data/tools/rips-scanner/result.json
-2022-03-11 14:38:48,873-INFO-task.puppytask: task result: /client/data/taskdirs/task_520/task_response.json

```

**Comment by T3st0r-Git** [comment]
工具包貌似自带了php呀    还需要我添加到环境变量或安装个php嘛

**Comment by owlmk** [comment]
可以安装个php，这里系统环境是什么可能是工具包的没能正常使用

**Comment by MRZHUH** [comment]
我也遇到类似问题，运行结果如下：
```2022-03-15 19:38:06,146-INFO-util.logutil: ['/root/CodeAnalysis/client/data/tools/linux-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/root/CodeAnalysis/client/data/taskdirs/task_347/scc_result_617d617ea45411ec8258dd7b6a6ae188.json', '/root/CodeAnalysis/client/code_dir']
2022-03-15 19:38:06,146-INFO-util.logutil: Task_347 (CustomFileScan) starts ...
2022-03-15 19:38:06,523-INFO-util.logutil: results written to /root/CodeAnalysis/client/data/taskdirs/task_347/scc_result_617d617ea45411ec8258dd7b6a6ae188.json
2022-03-15 19:38:16,252-INFO-util.logutil: Task_347 is done.
2022-03-15 19:38:16,505-INFO-util.logutil: 
****************************************************************************************************
代码分析结果: 
FileNotFoundError: [Errno 2] No such file or directory: '/root/CodeAnalysis/client/data/taskdirs/task_347_1/task_response.json'
****************************************************************************************************
2022-03-15 19:38:16,505-INFO-util.logutil: json report: /root/CodeAnalysis/client/scan_status.json
2022-03-15 19:38:16,505-ERROR-util.logutil: FileNotFoundError: [Errno 2] No such file or directory: '/root/CodeAnalysis/client/data/taskdirs/task_347_1/task_response.json'
Traceback (most recent call last):
  File "/root/CodeAnalysis/client/node/localrunner.py", line 396, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "/root/CodeAnalysis/client/node/localtask/runlocaltask.py", line 96, in scan_project
    self._proj_id).run()
  File "/root/CodeAnalysis/client/node/localtask/runtask.py", line 173, in run
    log_url, data_url)
  File "/root/CodeAnalysis/client/node/localtask/runtask.py", line 46, in get_task_result
    with open(task.response_file, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/root/CodeAnalysis/client/data/taskdirs/task_347_1/task_response.json'
```

clone日期： `2022年3月15日`

系统环境：
```
root@node10:~/CodeAnalysis/client# python --version
Python 3.7.12

root@node10:~/CodeAnalysis/client# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"


```

**Comment by bensonhome** [comment]
@MRZHUH 你直接python3命令进入python解释器，输入import pyaes，看看能找到模块吗？

**Comment by MRZHUH** [comment]
@bensonhome 
有的，模块存在
```
root@node10:~/CodeAnalysis/client# python
Python 3.7.12 (default, Mar 15 2022, 17:02:54) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyaes
>>> 

```

**Comment by MRZHUH** [comment]
@bensonhome 
经过老师提示，已经解决了问题，原因是系统中有多个python版本，使用python运行代码，但中间构建的时候会用到python3命令触发问题
```
root@node10:~/CodeAnalysis/client# whereis python3
python3: /usr/bin/python3 /usr/bin/python3.8 /usr/lib/python3 /usr/lib/python3.9 /usr/lib/python3.8 /etc/python3 /etc/python3.8 /usr/local/bin/python3 /usr/local/bin/python3.7m-config /usr/local/bin/python3.7-config /usr/local/bin/python3.7 /usr/local/bin/python3.7m /usr/local/lib/python3.8 /usr/local/lib/python3.7 /usr/local/python3 /usr/local/python3.7 /usr/share/python3 /usr/share/man/man1/python3.1.gz
root@node10:~/CodeAnalysis/client# whereis python
python: /usr/bin/python /usr/bin/python3.8 /usr/lib/python2.7 /usr/lib/python3.9 /usr/lib/python3.8 /etc/python3.8 /usr/local/bin/python3.7m-config /usr/local/bin/python /usr/local/bin/python3.7-config /usr/local/bin/python3.7 /usr/local/bin/python3.7m /usr/local/lib/python3.8 /usr/local/lib/python3.7 /usr/local/python3.7
root@node10:~/CodeAnalysis/client# ln -lh  /usr/bin/python3  /usr/bin/python 
ln: invalid option -- 'l'
Try 'ln --help' for more information.
root@node10:~/CodeAnalysis/client# ls -lh  /usr/bin/python3  /usr/bin/python 
lrwxrwxrwx 1 root root 30 Mar 15 17:06 /usr/bin/python -> /usr/local/python3/bin/python3
lrwxrwxrwx 1 root root 30 Mar 15 21:07 /usr/bin/python3 -> /usr/local/python3/bin/python3

```
