### ISSUE TITLE
执行扫描后，结果发送错误 method(send_proj_result) call fails on error

### ISSUE THREAD

**Issue by zu1662** [Tencent/CodeAnalysis#186]
Client执行代码分析，分析之后出现错误

`method(send_proj_result) call fails on error: HTTP Error 500: Internal Server Error`

具体错误如下：

```
2022-03-15 11:37:02,061-ERROR-util.wrapper: method(send_proj_result) call fails on error: HTTP Error 500: Internal Server Error
2022-03-15 11:37:02,061-WARNING-util.wrapper: method(send_proj_result) call still fails after 2 retries
2022-03-15 11:37:02,062-INFO-util.logutil: 
****************************************************************************************************
代码分析结果: 
HTTPError: HTTP Error 500: Internal Server Error
****************************************************************************************************
2022-03-15 11:37:02,063-INFO-util.logutil: json report: /home/CodeAnalysis/client/scan_status.json
2022-03-15 11:37:02,063-ERROR-util.logutil: HTTPError: HTTP Error 500: Internal Server Error
Traceback (most recent call last):
  File "/home/CodeAnalysis/client/node/localrunner.py", line 396, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "/home/CodeAnalysis/client/node/localtask/runlocaltask.py", line 119, in scan_project
    proj_scan_result, self._org_sid, self._team_name)
  File "/home/CodeAnalysis/client/node/localtask/resultsender.py", line 147, in send_result_to_server
    proj_result, org_sid, team_name)
  File "util/wrapper.py", line 20, in util.wrapper._MethodWrapper.__call__
  File "util/wrapper.py", line 40, in util.wrapper.SyncWrapper._call_method
  File "util/wrapper.py", line 42, in util.wrapper.SyncWrapper._call_method
  File "util/wrapper.py", line 51, in util.wrapper._RetryMethod.__call__
  File "util/wrapper.py", line 107, in util.wrapper.Retry.__retry_call
  File "util/wrapper.py", line 92, in util.wrapper.Retry.__retry_call
  File "/home/CodeAnalysis/client/util/api/dogapi.py", line 106, in send_proj_result
    rsp = CodeDogHttpClient(self._server_url, rel_url, headers=self._headers, json_data=scan_result).post()
  File "/home/CodeAnalysis/client/util/api/httpclient.py", line 78, in post
    result = HttpRequest.request(url=self.url, headers=self.headers, body=self.data, method="POST")
  File "/home/CodeAnalysis/client/util/api/httpclient.py", line 43, in request
    response = urlopen(req).read()
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/python3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

```

**Comment by Lingghh** [comment]
这里麻烦发一下main服务的报错相关日志哈

如果是本地部署的，可以参考这份文档:[Q&A-服务运行日志](https://github.com/Tencent/CodeAnalysis/blob/main/doc/Q%26A.md#123-%E6%9C%8D%E5%8A%A1%E8%BE%93%E5%87%BA%E6%97%A5%E5%BF%97%E6%89%BE%E4%B8%8D%E5%88%B0)
如果是docker-compose部署，可以执行
```
docker-compose exec main-server /bin/bash
cat log/codedog.log
```

**Comment by zu1662** [comment]
我看了日志。redis链接 失败了。。
