### ISSUE TITLE
[咨询/bug反馈] file模块使用minio作为数据存储后，localscan时服务端报错

### ISSUE THREAD

**Issue by anyuan95** [Tencent/CodeAnalysis#193]
按照说明文档，将配置的file服务改为minio作为存储后，执行localscan时报以下错误：
```
 -2022-03-23 19:01:14,091-DEBUG-codedog_file_server.authentication: [User: codedog] using mainserver proxy authen
 -2022-03-23 19:01:14,096-INFO-apps.filemgr.apis: [User: ] upload file, bucket: codedog, dir: public_server_temp, file: jobdata/projects/18/job124/86f64f5caa9811ecb3690a580a307db7/job_context.json
 -2022-03-23 19:01:14,099-INFO-apps.filemgr.core: [Bucket codedog] saving path: /tmp/tmps6uc0m1b.upload.json
 -2022-03-23 19:01:14,102-DEBUG-urllib3.connectionpool: http://10.48.188.63:9000 "PUT /codedog/public_server_temp/jobdata/projects/18/job124/86f64f5caa9811ecb3690a580a307db7/job_context.json HTTP/1.1" 200 0
 -2022-03-23 19:01:14,102-INFO-apps.filemgr.apis: Current file md5: <minio.helpers.ObjectWriteResult object at 0x7f63e0affb10>
 -2022-03-23 19:01:14,102-INFO-apps.filemgr.core: ################## header_md5 ##################= 5ffce803888cf538d452ce553a32f026
 -2022-03-23 19:01:14,102-ERROR-utils.handler: 上传失败，文件MD5值与头部MD5值不一致
 Traceback (most recent call last):
   File "/home/asmallcompany/.local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
     response = handler(request, *args, **kwargs)
   File "/docker/opt/asmallcompany/codeanalysis/server/projects/file/apps/filemgr/apis.py", line 147, in put
     raise error.QFSFileUploadError("上传失败，文件MD5值与头部MD5值不一致")
 utils.error.QFSFileUploadError: 上传失败，文件MD5值与头部MD5值不一致
 -2022-03-23 19:01:14,103-ERROR-utils.handler: [QFSRequestError][Err: upload_error] msg: 上传失败，文件MD5值与头部MD5值不一致
 Traceback (most recent call last):
   File "/home/asmallcompany/.local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
     response = handler(request, *args, **kwargs)
   File "/docker/opt/asmallcompany/codeanalysis/server/projects/file/apps/filemgr/apis.py", line 147, in put
     raise error.QFSFileUploadError("上传失败，文件MD5值与头部MD5值不一致")
 utils.error.QFSFileUploadError: 上传失败，文件MD5值与头部MD5值不一致
 -2022-03-23 19:01:14,103-ERROR-django.request: Internal Server Error: /api/files/codedog/public_server_temp/jobdata/projects/18/job124/86f64f5caa9811ecb3690a580a307db7/job_context.json
```

添加日志将content_md5和header_md5比较发现，二者的数据结构不同：
-2022-03-23 19:01:14,102-INFO-apps.filemgr.apis: Current file md5: <minio.helpers.ObjectWriteResult object at 0x7f63e0affb10>
-2022-03-23 19:01:14,102-INFO-apps.filemgr.core: ################## header_md5 ##################= 5ffce803888cf538d452ce553a32f026

我将这行代码
https://github.com/Tencent/CodeAnalysis/blob/2abf20e1c6ee9c97a9a478736103ac13316a8165/server/projects/file/utils/file_storage/minio.py#L215
修改为
`return True, '', result.http_headers.get('Etag').replace('"', '')`
似乎就可以了。

我不太清楚这里设计时是计划怎么获取minio上传后的md5，请Authors帮忙看下。

运行环境：
CodeAnalysis：COMMIT=55656837
Minio: RELEASE.2022-03-22T02-05-10Z
Minio Server System: CentOS Linux release 7.6.1810 (Core)
File Server System: CentOS Linux release 7.6.1810 (Core)

**Comment by anyuan95** [comment]
想问下现在对minio的支持是不是还没有开发完？
我按照上面描述的方式修改之后，上面的MD5检查不报错了，但是又出现了新的报错：
```
==> codedog_error_ftp.log <==
-2022-03-24 15:20:16,089-ERROR-django.request: Internal Server Error: /api/files/codedog/public_server_temp/jobdata/projects/18/job148/d780662eab4211ecb06b0a580a307db7/task_params_574.json
Traceback (most recent call last):
  File "/home/sankuai/.local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/sankuai/.local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sankuai/.local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sankuai/.local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sankuai/.local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/sankuai/.local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/sankuai/.local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/sankuai/.local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/docker/opt/meituan/codeanalysis/server/projects/file/apps/filemgr/apis.py", line 176, in get
    is_downloaded, msg, size = core.FileDownloadHandler.download_from_local(bucket, dir_path, file_name)
  File "/docker/opt/meituan/codeanalysis/server/projects/file/apps/filemgr/core.py", line 233, in download_from_local
    local_full_path = storage_client.format_real_file_name(bucket, '%s/%s' % (dir_path, file_name))
AttributeError: 'MinioStorageClient' object has no attribute 'format_real_file_name'
```

**Comment by Lingghh** [comment]
这里对minio的兼容有一些问题，我们处理一下

**Comment by anyuan95** [comment]
BTW，想请教一下这个文件是要如何使用的？我好像并没有在任何脚本中找到操作这个文件的地方。server/configs/nginx/tca_file_minio.conf

**Comment by Lingghh** [comment]
``tca_file_minio.conf``和``tca_file_local.conf``分别代表基于minio和本地进行存储，两者是相互替代的

**Comment by anyuan95** [comment]
但是我在初始化脚本中只找到了使用tca_file_local.conf的逻辑，而并没有找到使用tca_file_minio.conf的逻辑。
如果可以的话希望将tca_file_minio.conf文件的支持也添加到初始化脚本中。

**Comment by Lingghh** [comment]
这一块正在处理哈

**Comment by Lingghh** [comment]
可以更新代码，查阅一下[minio配置文档]哈(https://github.com/Tencent/CodeAnalysis/blob/main/doc/deploy_with_minio.md)

目前需要手动调整minio的配置信息，添加到初始化脚本正在评估哈
