### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by quanwangshushang** [Tencent/CodeAnalysis#244]
启动分析报错 HTTP Error 404: Not Found

url: http://192.168.106.73/server/main/api/orgs/I0n0lEi6suY/teams/hlleuser-ios/repos/12/projects/26/jobs/70/tasksbeat/
2022-04-19 10:42:11,086-ERROR-util.wrapper: method(job_heart_beat) call fails on error: HTTP Error 404: Not Found
2022-04-19 10:42:11,086-WARNING-util.wrapper: method(job_heart_beat) call still fails after 2 retries
Exception in thread Thread-55:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "node/localtask/jobheartbeat.py", line 40, in run
  File "util/wrapper.py", line 20, in util.wrapper._MethodWrapper.__call__
  File "util/wrapper.py", line 40, in util.wrapper.SyncWrapper._call_method
  File "util/wrapper.py", line 42, in util.wrapper.SyncWrapper._call_method
  File "util/wrapper.py", line 51, in util.wrapper._RetryMethod.__call__
  File "util/wrapper.py", line 107, in util.wrapper.Retry.__retry_call
  File "util/wrapper.py", line 92, in util.wrapper.Retry.__retry_call
  File "util/api/dogapi.py", line 55, in job_heart_beat
  File "util/api/httpclient.py", line 85, in post
  File "util/api/httpclient.py", line 43, in request
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 531, in open
  File "urllib/request.py", line 641, in http_response
  File "urllib/request.py", line 569, in error
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 649, in http_error_default
urllib.error.HTTPError: HTTP Error 404: Not Found

[Tools init]: 100%|███████████████████████████████████████████████████| 9/9 [00:18<00:00,  2.01s/it]
2022-04-19 10:42:15,546-INFO-util.logutil: Initialize tools done.(use time: 18.70s)
2022-04-19 10:42:15,546-INFO-util.logutil: 
****************************************************************************************************
代码分析结果: 
KeyError: 'team_name'
****************************************************************************************************
2022-04-19 10:42:15,546-INFO-util.logutil: json report: /Users/huolala/Documents/JKS/tca-client-20220418_1-x86_64-apple-darwin/scan_status.json
2022-04-19 10:42:15,547-ERROR-util.logutil: KeyError: 'team_name'
Traceback (most recent call last):
  File "node/localtask/localrunner.py", line 378, in run
  File "node/localtask/requestgenerator.py", line 153, in generate_request
  File "node/localtask/requestgenerator.py", line 172, in _get_execute_request_list
  File "node/localtask/requestmodify.py", line 32, in add_params
KeyError: 'team_name'
➜  tca-client-20220418_1-x86_64-apple-darwin client_loop: send disconnect: Broken pipe

**Comment by Lingghh** [comment]
这里的执行方式是本地启动客户端还是在页面启动呢？

**Comment by quanwangshushang** [comment]
> 这里的执行方式是本地启动客户端还是在页面启动呢？

客户端，应该是客户端的版本和服务端版本不匹配导致的

**Comment by Lingghh** [comment]
部署最新版本的代码是否可以解决呢？
