### ISSUE TITLE
本地扫描：不包含.svn或.git目录,不是有效代码库!

### ISSUE THREAD

**Issue by G3G4X5X6** [Tencent/CodeAnalysis#290]
![image](https://user-images.githubusercontent.com/87740076/166888165-4f33c2e7-a7e8-435d-b07e-24d7da6ffb82.png)
```shell
[root@localhost client]# python3 codepuppy.py localscan
2022-05-05 04:32:19,584-INFO-util.logutil: Tencent Cloud Code Analysis (OpenSource Beta)
2022-05-05 04:32:19,596-INFO-util.logutil: Python 3.7.13
2022-05-05 04:32:19,695-INFO-util.logutil: ------------------------------
2022-05-05 04:32:19,695-INFO-util.logutil:  #######    ####      # 
2022-05-05 04:32:19,695-INFO-util.logutil:     #      #    #     # 
2022-05-05 04:32:19,695-INFO-util.logutil:     #     #          ### 
2022-05-05 04:32:19,696-INFO-util.logutil:     #     #          # # 
2022-05-05 04:32:19,696-INFO-util.logutil:     #     #         #####
2022-05-05 04:32:19,696-INFO-util.logutil:     #      #    #   #   #
2022-05-05 04:32:19,696-INFO-util.logutil:     #       ####   ##   ##
2022-05-05 04:32:19,696-INFO-util.logutil: ------------------------------
2022-05-05 04:32:19,772-INFO-util.logutil: using config file: /root/CodeAnalysis/client/codedog.ini
2022-05-05 04:32:19,774-INFO-util.logutil: connect to server: http://192.168.30.136/
2022-05-05 04:32:19,774-INFO-util.logutil: 
****************************************************************************************************
代码分析结果: 
NodeError: Error[204]: 代码目录(/root/source_dir)下不包含.svn或.git目录,不是有效代码库!
****************************************************************************************************
2022-05-05 04:32:19,774-INFO-util.logutil: json report: /root/CodeAnalysis/client/scan_status.json
2022-05-05 04:32:19,774-ERROR-util.logutil: NodeError: Error[204]: 代码目录(/root/source_dir)下不包含.svn或.git目录,不是有效代码库!
Traceback (most recent call last):
  File "/root/CodeAnalysis/client/node/localtask/localrunner.py", line 340, in run
    self.__check_config_info()
  File "/root/CodeAnalysis/client/node/localtask/localrunner.py", line 280, in __check_config_info
    msg="代码目录(%s)下不包含.svn或.git目录,不是有效代码库!" % self._source_dir)
util.exceptions.NodeError: Error[204]: 代码目录(/root/source_dir)下不包含.svn或.git目录,不是有效代码库!

```
有点不理解，本地扫描不是源码在source_dir目录下吗？为什么会有检查是否是一个代码库的需求？

**Comment by zhang9w0v5** [comment]
因为研发管理需要，如果没用代码库进行管理代码，那么代码就属于一种无系统管理的游离状态。
在进一步分析责任人和引入时间时，缺少了一些管理依据。

一般项目都会有代码管理，如果是涉及多人协作开发，或者继承开发，代码管理是比较硬的需求。

**Comment by G3G4X5X6** [comment]
了解，谢谢！
