### ISSUE TITLE
安装启动报错

### ISSUE THREAD

**Issue by liweihui1** [Tencent/CodeAnalysis#296]
重新安装启动报错
![1652078897797_A3D8CE8C-07AA-4c33-84A8-288D8006AD5A](https://user-images.githubusercontent.com/67351176/167358803-06506bae-bf0d-4351-9ee6-cb70ec715c6a.png)

docker-compose exec main-server /bin/bash
tail -n 200 log/codedog_error.logroot@799d90deaac5:/var/www/django/codedog# tail -n 200 log/codedog_error.log
Traceback (most recent call last):
  File "/var/www/django/codedog/apps/codeproj/apis/v3.py", line 971, in post
    project, creator=UserManager.get_username(request.user), scan_data=slz.validated_data)
  File "/var/www/django/codedog/apps/codeproj/core/base.py", line 125, in create_server_scan
    job.context = job_context
  File "/var/www/django/codedog/apps/job/models/base.py", line 178, in context
    raise CDErrorBase(errcode.E_SERVER_FILE_SERVICE_ERROR, "文件服务器异常")
util.exceptions.CDErrorBase: [116]文件服务器异常
-2022-05-09 14:51:13,164-ERROR-util.retrylib: method <put_file> exception: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job4/4771d78ecf6411ec963f0242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/var/www/django/codedog/util/retrylib.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/var/www/django/codedog/util/fileserver.py", line 90, in put_file
    rsp = self._http_client.put(file_url, data=data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 47, in put
    result = self.session("PUT", path, params=params, data=data, json_data=json_data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 36, in session
    return self._http_client.request(method, path, fields=params, headers=headers, body=data)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job4/4771d78ecf6411ec963f0242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
-2022-05-09 14:51:13,165-ERROR-apps.job.models.base: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job4/4771d78ecf6411ec963f0242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/var/www/django/codedog/apps/job/models/base.py", line 174, in context
    context_url = file_server.put_file(json.dumps(context), context_path, file_server.TypeEnum.TEMPORARY)
  File "/var/www/django/codedog/util/retrylib.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/var/www/django/codedog/util/fileserver.py", line 90, in put_file
    rsp = self._http_client.put(file_url, data=data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 47, in put
    result = self.session("PUT", path, params=params, data=data, json_data=json_data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 36, in session
    return self._http_client.request(method, path, fields=params, headers=headers, body=data)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job4/4771d78ecf6411ec963f0242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
-2022-05-09 14:51:13,396-ERROR-apps.codeproj.apis.v3: [116]文件服务器异常
Traceback (most recent call last):
  File "/var/www/django/codedog/apps/job/models/base.py", line 174, in context
    context_url = file_server.put_file(json.dumps(context), context_path, file_server.TypeEnum.TEMPORARY)
  File "/var/www/django/codedog/util/retrylib.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/var/www/django/codedog/util/fileserver.py", line 90, in put_file
    rsp = self._http_client.put(file_url, data=data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 47, in put
    result = self.session("PUT", path, params=params, data=data, json_data=json_data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 36, in session
    return self._http_client.request(method, path, fields=params, headers=headers, body=data)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job4/4771d78ecf6411ec963f0242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/django/codedog/apps/codeproj/apis/v3.py", line 971, in post
    project, creator=UserManager.get_username(request.user), scan_data=slz.validated_data)
  File "/var/www/django/codedog/apps/codeproj/core/base.py", line 125, in create_server_scan
    job.context = job_context
  File "/var/www/django/codedog/apps/job/models/base.py", line 178, in context
    raise CDErrorBase(errcode.E_SERVER_FILE_SERVICE_ERROR, "文件服务器异常")
util.exceptions.CDErrorBase: [116]文件服务器异常
-2022-05-09 14:57:41,370-ERROR-util.retrylib: method <put_file> exception: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job5/2f086cc0cf6511ec89b30242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/var/www/django/codedog/util/retrylib.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/var/www/django/codedog/util/fileserver.py", line 90, in put_file
    rsp = self._http_client.put(file_url, data=data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 47, in put
    result = self.session("PUT", path, params=params, data=data, json_data=json_data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 36, in session
    return self._http_client.request(method, path, fields=params, headers=headers, body=data)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job5/2f086cc0cf6511ec89b30242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
-2022-05-09 14:57:41,375-ERROR-apps.job.models.base: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job5/2f086cc0cf6511ec89b30242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
Traceback (most recent call last):
  File "/var/www/django/codedog/apps/job/models/base.py", line 174, in context
    context_url = file_server.put_file(json.dumps(context), context_path, file_server.TypeEnum.TEMPORARY)
  File "/var/www/django/codedog/util/retrylib.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/var/www/django/codedog/util/fileserver.py", line 90, in put_file
    rsp = self._http_client.put(file_url, data=data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 47, in put
    result = self.session("PUT", path, params=params, data=data, json_data=json_data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 36, in session
    return self._http_client.request(method, path, fields=params, headers=headers, body=data)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job5/2f086cc0cf6511ec89b30242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))
-2022-05-09 14:57:41,444-ERROR-apps.codeproj.apis.v3: [116]文件服务器异常
Traceback (most recent call last):
  File "/var/www/django/codedog/apps/job/models/base.py", line 174, in context
    context_url = file_server.put_file(json.dumps(context), context_path, file_server.TypeEnum.TEMPORARY)
  File "/var/www/django/codedog/util/retrylib.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/var/www/django/codedog/util/fileserver.py", line 90, in put_file
    rsp = self._http_client.put(file_url, data=data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 47, in put
    result = self.session("PUT", path, params=params, data=data, json_data=json_data, headers=headers)
  File "/var/www/django/codedog/util/httpclient.py", line 36, in session
    return self._http_client.request(method, path, fields=params, headers=headers, body=data)
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 859, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 836, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='nginx', port=8000): Max retries exceeded with url: /files/public_server_temp/jobdata/projects/1/job5/2f086cc0cf6511ec89b30242ac130006/job_context.json (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/django/codedog/apps/codeproj/apis/v3.py", line 971, in post
    project, creator=UserManager.get_username(request.user), scan_data=slz.validated_data)
  File "/var/www/django/codedog/apps/codeproj/core/base.py", line 125, in create_server_scan
    job.context = job_context
  File "/var/www/django/codedog/apps/job/models/base.py", line 178, in context
    raise CDErrorBase(errcode.E_SERVER_FILE_SERVICE_ERROR, "文件服务器异常")
util.exceptions.CDErrorBase: [116]文件服务器异常

**Comment by Lingghh** [comment]
这里还需要麻烦提供一下 file-server 的日志
```
docker-compose exec file-server /bin/bash
tail -n 200 log/codedog_file.log
```

**Comment by liweihui1** [comment]
[root@test-whitebox-009030 CodeAnalysis-main]# docker-compose exec file-server /bin/bash
root@a3022d38277a:/var/www/django/codedog# tail -n 200 log/codedog_file.log
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'codedog_file.authenmgr_userprofile' doesn't exist")
-2022-05-09 14:57:41,313-DEBUG-codedog_file_server.authentication: [User: codedog] using mainserver proxy authen
-2022-05-09 14:57:41,323-ERROR-utils.handler: (1146, "Table 'codedog_file.authenmgr_userprofile' doesn't exist")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'codedog_file.authenmgr_userprofile' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/var/www/django/codedog/codedog_file_server/authentication.py", line 89, in authenticate
    user = User.objects.get_or_create(nickname=username)[0]
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'codedog_file.authenmgr_userprofile' doesn't exist")
-2022-05-09 14:57:41,325-ERROR-django.request: Internal Server Error: /api/files/codedog/public_server_temp/jobdata/projects/1/job5/2f086cc0cf6511ec89b30242ac130006/job_context.json
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'codedog_file.authenmgr_userprofile' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 410, in initial
    self.perform_authentication(request)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 324, in perform_authentication
    request.user
  File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 220, in user
    self._authenticate()
  File "/usr/local/lib/python3.7/site-packages/rest_framework/request.py", line 373, in _authenticate
    user_auth_tuple = authenticator.authenticate(self)
  File "/var/www/django/codedog/codedog_file_server/authentication.py", line 89, in authenticate
    user = User.objects.get_or_create(nickname=username)[0]
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'codedog_file.authenmgr_userprofile' doesn't exist")

**Comment by Lingghh** [comment]
麻烦执行一下``./compose_init.sh``脚本

**Comment by Lingghh** [comment]
在执行``quick_install.sh``脚本时有出现什么错误么？

**Comment by liweihui1** [comment]
有的，需要自己先安装好docker

**Comment by liweihui1** [comment]
否则好像因为网络源原因还是网络原因，一直执行失败

**Comment by Lingghh** [comment]
> 否则好像因为网络源原因还是网络原因，一直执行失败

这里方便提供一下错误日志么？我们分析看看
