### ISSUE TITLE
执行结果：节点端SCM任务故障 NodeError: Error[203]: fatal: Authentication failed for报错执行失败

### ISSUE THREAD

**Issue by liweihui1** [Tencent/CodeAnalysis#297]
![image](https://user-images.githubusercontent.com/67351176/167363272-543f5e25-b352-46e5-8192-ba5b55267e95.png)

**Comment by liweihui1** [comment]
-2022-05-09 15:40:03,642-INFO-util.logutil: start to run task: Kunlun-M, execute_processes: ['analyze', 'datahandle']
-2022-05-09 15:40:05,008-ERROR-util.pathlib: file not exist: /home/iotmp/CodeAnalysis-main/client/../tools/puppy-tools-config
-2022-05-09 15:40:05,401-WARNING-task.puppytask: task status code is 203
-2022-05-09 15:40:05,402-WARNING-task.puppytask: task messsage: NodeError: Error[203]: fatal: Authentication failed for 'https://git.code.tencent.com/TCA/tca-tools/puppy-tools-config.git/'
-2022-05-09 15:40:05,402-INFO-task.puppytask: task result: /home/iotmp/CodeAnalysis-main/client/data/taskdirs/task_1/task_response.json
执行日志

**Comment by liweihui1** [comment]
-2022-05-09 15:31:36,647-INFO-celery.worker.consumer.connection: Connected to redis://redis:6379/1
-2022-05-09 15:31:36,652-INFO-celery.worker.consumer.mingle: mingle: searching for neighbors
-2022-05-09 15:31:37,663-INFO-celery.worker.consumer.mingle: mingle: all alone
-2022-05-09 15:34:29,707-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.handle_expired_job[aa2b76bc-994f-4c91-bc95-493d7317ae72] received
-2022-05-09 15:34:29,725-INFO-celery.worker.strategy: Task apps.codeproj.tasks.base.handle_scheduled_projects[89a78722-c10b-4612-858b-291835bd82ea] received
-2022-05-09 15:34:29,729-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_closing_job[67b9e4a6-d47a-4008-b959-bb3171e8db2c] received
-2022-05-09 15:34:29,732-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询未关闭的超时任务，当前未关闭任务数: 0
-2022-05-09 15:34:29,733-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_running_job[22012547-1d63-49cc-86eb-baf8a492180e] received
-2022-05-09 15:34:29,740-INFO-apps.job.tasks.jobcheck: [PeriodicTasks] 开始查询未上报心跳的客户端任务: 0
-2022-05-09 15:34:29,745-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询未确认的Task任务，当前未确认Task任务数: 0
-2022-05-09 15:34:29,754-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_initing_job[cab7fbc4-f03b-4440-a242-9e0dcd54a2d0] received
-2022-05-09 15:34:29,976-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.handle_expired_job[aa2b76bc-994f-4c91-bc95-493d7317ae72] succeeded in 0.2622132799588144s: None
-2022-05-09 15:34:29,986-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询入库中的任务，当前入库中的任务数: 0
-2022-05-09 15:34:29,989-INFO-celery.app.trace: Task apps.codeproj.tasks.base.handle_scheduled_projects[89a78722-c10b-4612-858b-291835bd82ea] succeeded in 0.25697269896045327s: None
-2022-05-09 15:34:30,001-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询执行中的任务，当前运行中的任务数: 0
-2022-05-09 15:34:30,017-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_closing_job[67b9e4a6-d47a-4008-b959-bb3171e8db2c] succeeded in 0.037740387953817844s: None
-2022-05-09 15:34:30,027-INFO-apps.job.tasks.jobcheck: 当前有0个任务初始化超时
-2022-05-09 15:34:30,233-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_running_job[22012547-1d63-49cc-86eb-baf8a492180e] succeeded in 0.24033047002740204s: None
-2022-05-09 15:34:30,244-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_initing_job[cab7fbc4-f03b-4440-a242-9e0dcd54a2d0] succeeded in 0.2244512028992176s: None
-2022-05-09 15:34:30,360-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[42dd87e8-810b-418e-ac40-051740af65c8] received
-2022-05-09 15:34:30,414-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[42dd87e8-810b-418e-ac40-051740af65c8] succeeded in 0.05248899385333061s: None
-2022-05-09 15:37:30,476-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[1924945b-0461-4890-9b99-9a6f445c49d8] received
-2022-05-09 15:37:30,531-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[1924945b-0461-4890-9b99-9a6f445c49d8] succeeded in 0.049004963133484125s: None
-2022-05-09 15:39:29,856-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_initing_job[e79f2a87-55ad-4562-b1a0-052fccc65b94] received
-2022-05-09 15:39:29,879-INFO-apps.job.tasks.jobcheck: 当前有0个任务初始化超时
-2022-05-09 15:39:29,932-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_initing_job[e79f2a87-55ad-4562-b1a0-052fccc65b94] succeeded in 0.07136178808286786s: None
-2022-05-09 15:39:35,541-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.start_server_job[e8f1db67-c6b8-471d-a8bb-b44eaa15a30e] received
-2022-05-09 15:39:35,910-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 6]开始初始化任务参数
-2022-05-09 15:39:35,958-INFO-apps.codeproj.core.jobmgr: [Project: 1]开始获取codelint参数
-2022-05-09 15:39:36,152-INFO-apps.codeproj.core.jobmgr: [Project: 1]开始获取codemetric参数
-2022-05-09 15:39:36,202-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 6]开始获取Scm信息
-2022-05-09 15:39:36,202-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:39:51,327-INFO-apps.codeproj.core.jobmgr: [a5e507bd12ebe98baddba3d5aeee2dce0008d25e] 使用最新版本号
-2022-05-09 15:39:52,640-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:39:52,640-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:39:52,640-INFO-apps.codeproj.core.jobmgr: Auth type: password[17374574108]
-2022-05-09 15:39:52,640-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:39:52,641-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:39:52,705-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 6]更新Analysis服务器的Scan信息
-2022-05-09 15:39:52,705-INFO-util.webclients: 调用analyse server接口：api/projects/1/scans/1/info/，参数如下：
-2022-05-09 15:39:52,706-INFO-util.webclients: {
  "current_revision": "a5e507bd12ebe98baddba3d5aeee2dce0008d25e",
  "scm_time": "2019-12-16 21:58:21",
  "state": 1
}
-2022-05-09 15:39:52,766-INFO-apps.codeproj.core.jobmgr: AnalyseServer更新scan返回结果：scan_id=1，详情如下:
-2022-05-09 15:39:52,766-INFO-apps.codeproj.core.jobmgr: {'id': 1, 'repo_id': 1, 'project_id': 1, 'job_gid': 6, 'scan_time': '2022-05-09T15:39:35.240093+08:00', 'state': 1, 'type': 1, 'current_revision': 'a5e507bd12ebe98baddba3d5aeee2dce0008d25e', 'result_code': None, 'result_msg': None, 'create_time': '2022-05-09T15:39:32.069578+08:00', 'creator': 'CodeDog', 'execute_time': '16.759907', 'waiting_time': '3.170515', 'total_time': '19.930422', 'status': None, 'text': None, 'url': '', 'description': None, 'lintscan': None, 'duplicatescan': None, 'cyclomaticcomplexityscan': None, 'clocscan': None, 'result_code_msg': None, 'daily_save': False, 'job_archived': None}
-2022-05-09 15:39:52,767-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 6]开始创建Task
-2022-05-09 15:39:58,852-INFO-apps.codeproj.core.jobmgr: job[6]创建完成，尝试结束任务...
-2022-05-09 15:39:58,853-INFO-apps.job.core.base: [Job: 6] start close_job ...
-2022-05-09 15:39:58,857-INFO-apps.job.core.base: [Job: 6] get scan_id is 1
-2022-05-09 15:39:58,857-INFO-apps.job.core.base: [Job: 6] checking task_done number (0/4)...
-2022-05-09 15:39:58,857-INFO-apps.job.core.base: [Job: 6] check failed. task_done(0) less than task_num(4). end of close_job.
-2022-05-09 15:39:58,950-INFO-apps.job.core.base: [Job: 6] start to add job to queue...
-2022-05-09 15:39:59,421-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.start_server_job[e8f1db67-c6b8-471d-a8bb-b44eaa15a30e] succeeded in 23.878103223163635s: None
-2022-05-09 15:40:30,519-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[28ebd4f0-ba0c-438a-80bb-35f45ff3d2a7] received
-2022-05-09 15:40:30,678-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[28ebd4f0-ba0c-438a-80bb-35f45ff3d2a7] succeeded in 0.15308621991425753s: None
-2022-05-09 15:43:30,587-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[3fd6775e-fbfd-4e83-8494-e044c7a7e69d] received
-2022-05-09 15:43:30,624-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[3fd6775e-fbfd-4e83-8494-e044c7a7e69d] succeeded in 0.034228858072310686s: None
-2022-05-09 15:44:29,765-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.handle_expired_job[819a6dcf-cb0f-43c2-a6a6-f444da47b5f3] received
-2022-05-09 15:44:29,769-INFO-celery.worker.strategy: Task apps.codeproj.tasks.base.handle_scheduled_projects[22278ea1-1297-4691-9fee-a7166eedd24a] received
-2022-05-09 15:44:29,779-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询未关闭的超时任务，当前未关闭任务数: 0
-2022-05-09 15:44:29,787-INFO-apps.job.tasks.jobcheck: [PeriodicTasks] 开始查询未上报心跳的客户端任务: 0
-2022-05-09 15:44:29,794-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询未确认的Task任务，当前未确认Task任务数: 0
-2022-05-09 15:44:29,844-INFO-celery.app.trace: Task apps.codeproj.tasks.base.handle_scheduled_projects[22278ea1-1297-4691-9fee-a7166eedd24a] succeeded in 0.0675287249032408s: None
-2022-05-09 15:44:29,856-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_initing_job[3c5e79f5-4468-482c-ab0f-a572c59b62a0] received
-2022-05-09 15:44:29,862-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.handle_expired_job[819a6dcf-cb0f-43c2-a6a6-f444da47b5f3] succeeded in 0.09042424499057233s: None
-2022-05-09 15:44:29,866-INFO-apps.job.tasks.jobcheck: 当前有0个任务初始化超时
-2022-05-09 15:44:29,907-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_initing_job[3c5e79f5-4468-482c-ab0f-a572c59b62a0] succeeded in 0.04985718405805528s: None
-2022-05-09 15:46:30,684-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[d38b9ab9-60fe-479a-9517-663de76e7b01] received
-2022-05-09 15:46:30,718-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[d38b9ab9-60fe-479a-9517-663de76e7b01] succeeded in 0.031106743030250072s: None
-2022-05-09 15:49:29,954-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_initing_job[7ab1c172-4907-4b77-b1f0-cf44ed4fc4fc] received
-2022-05-09 15:49:29,968-INFO-apps.job.tasks.jobcheck: 当前有0个任务初始化超时
-2022-05-09 15:49:30,021-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_initing_job[7ab1c172-4907-4b77-b1f0-cf44ed4fc4fc] succeeded in 0.06343149091117084s: None
-2022-05-09 15:49:30,689-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[f205807a-e0d6-4051-8733-842d60c55243] received
-2022-05-09 15:49:30,720-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[f205807a-e0d6-4051-8733-842d60c55243] succeeded in 0.02957750204950571s: None
-2022-05-09 15:50:33,504-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.start_server_job[c0e4ebf6-7f7d-448b-980e-93f760ba6595] received
-2022-05-09 15:50:33,695-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 7]开始初始化任务参数
-2022-05-09 15:50:33,733-INFO-apps.codeproj.core.jobmgr: [Project: 1]开始获取codelint参数
-2022-05-09 15:50:33,810-INFO-apps.codeproj.core.jobmgr: [Project: 1]开始获取codemetric参数
-2022-05-09 15:50:33,853-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 7]开始获取Scm信息
-2022-05-09 15:50:33,854-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:50:35,162-INFO-apps.codeproj.core.jobmgr: [a5e507bd12ebe98baddba3d5aeee2dce0008d25e] 使用最新版本号
-2022-05-09 15:50:36,605-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:50:36,605-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:50:36,605-INFO-apps.codeproj.core.jobmgr: Auth type: password[17374574108]
-2022-05-09 15:50:36,606-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:50:36,606-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:50:36,635-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 7]更新Analysis服务器的Scan信息
-2022-05-09 15:50:36,636-INFO-util.webclients: 调用analyse server接口：api/projects/1/scans/2/info/，参数如下：
-2022-05-09 15:50:36,636-INFO-util.webclients: {
  "current_revision": "a5e507bd12ebe98baddba3d5aeee2dce0008d25e",
  "scm_time": "2019-12-16 21:58:21",
  "state": 1
}
-2022-05-09 15:50:36,695-INFO-apps.codeproj.core.jobmgr: AnalyseServer更新scan返回结果：scan_id=2，详情如下:
-2022-05-09 15:50:36,695-INFO-apps.codeproj.core.jobmgr: {'id': 2, 'repo_id': 1, 'project_id': 1, 'job_gid': 7, 'scan_time': '2022-05-09T15:50:33.244786+08:00', 'state': 1, 'type': 1, 'current_revision': 'a5e507bd12ebe98baddba3d5aeee2dce0008d25e', 'result_code': None, 'result_msg': None, 'create_time': '2022-05-09T15:50:32.901544+08:00', 'creator': 'CodeDog', 'execute_time': '2.755214', 'waiting_time': '0.343242', 'total_time': '3.098456', 'status': None, 'text': None, 'url': '', 'description': None, 'lintscan': None, 'duplicatescan': None, 'cyclomaticcomplexityscan': None, 'clocscan': None, 'result_code_msg': None, 'daily_save': False, 'job_archived': None}
-2022-05-09 15:50:36,696-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 7]开始创建Task
-2022-05-09 15:50:39,593-INFO-apps.codeproj.core.jobmgr: job[7]创建完成，尝试结束任务...
-2022-05-09 15:50:39,593-INFO-apps.job.core.base: [Job: 7] start close_job ...
-2022-05-09 15:50:39,597-INFO-apps.job.core.base: [Job: 7] get scan_id is 2
-2022-05-09 15:50:39,598-INFO-apps.job.core.base: [Job: 7] checking task_done number (0/4)...
-2022-05-09 15:50:39,598-INFO-apps.job.core.base: [Job: 7] check failed. task_done(0) less than task_num(4). end of close_job.
-2022-05-09 15:50:39,621-INFO-apps.job.core.base: [Job: 7] start to add job to queue...
-2022-05-09 15:50:39,870-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.start_server_job[c0e4ebf6-7f7d-448b-980e-93f760ba6595] succeeded in 6.3629318999592215s: None
-2022-05-09 15:52:30,739-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[9dd6bf50-bd43-4f4d-be2a-14616a4fa987] received
-2022-05-09 15:52:30,775-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[9dd6bf50-bd43-4f4d-be2a-14616a4fa987] succeeded in 0.03249792009592056s: None
-2022-05-09 15:53:44,481-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.start_server_job[7aab0a13-78e9-4b20-89c9-440cdde9f9d9] received
-2022-05-09 15:53:44,660-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 8]开始初始化任务参数
-2022-05-09 15:53:44,691-INFO-apps.codeproj.core.jobmgr: [Project: 1]开始获取codelint参数
-2022-05-09 15:53:44,768-INFO-apps.codeproj.core.jobmgr: [Project: 1]开始获取codemetric参数
-2022-05-09 15:53:44,809-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 8]开始获取Scm信息
-2022-05-09 15:53:44,810-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:53:47,479-INFO-apps.codeproj.core.jobmgr: [a5e507bd12ebe98baddba3d5aeee2dce0008d25e] 使用最新版本号
-2022-05-09 15:53:48,955-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:53:48,956-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:53:48,956-INFO-apps.codeproj.core.jobmgr: Auth type: password[17374574108]
-2022-05-09 15:53:48,956-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:53:48,956-INFO-apps.codeproj.models.base: using repo scm_auth
-2022-05-09 15:53:48,979-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 8]更新Analysis服务器的Scan信息
-2022-05-09 15:53:48,980-INFO-util.webclients: 调用analyse server接口：api/projects/1/scans/3/info/，参数如下：
-2022-05-09 15:53:48,980-INFO-util.webclients: {
  "current_revision": "a5e507bd12ebe98baddba3d5aeee2dce0008d25e",
  "scm_time": "2019-12-16 21:58:21",
  "state": 1
}
-2022-05-09 15:53:49,055-INFO-apps.codeproj.core.jobmgr: AnalyseServer更新scan返回结果：scan_id=3，详情如下:
-2022-05-09 15:53:49,056-INFO-apps.codeproj.core.jobmgr: {'id': 3, 'repo_id': 1, 'project_id': 1, 'job_gid': 8, 'scan_time': '2022-05-09T15:53:44.386382+08:00', 'state': 1, 'type': 1, 'current_revision': 'a5e507bd12ebe98baddba3d5aeee2dce0008d25e', 'result_code': None, 'result_msg': None, 'create_time': '2022-05-09T15:53:43.936414+08:00', 'creator': 'CodeDog', 'execute_time': '4.613618', 'waiting_time': '0.449968', 'total_time': '5.063586', 'status': None, 'text': None, 'url': '', 'description': None, 'lintscan': None, 'duplicatescan': None, 'cyclomaticcomplexityscan': None, 'clocscan': None, 'result_code_msg': None, 'daily_save': False, 'job_archived': None}
-2022-05-09 15:53:49,056-INFO-apps.codeproj.core.jobmgr: [Project: 1][Job: 8]开始创建Task
-2022-05-09 15:53:51,123-INFO-apps.codeproj.core.jobmgr: job[8]创建完成，尝试结束任务...
-2022-05-09 15:53:51,123-INFO-apps.job.core.base: [Job: 8] start close_job ...
-2022-05-09 15:53:51,128-INFO-apps.job.core.base: [Job: 8] get scan_id is 3
-2022-05-09 15:53:51,128-INFO-apps.job.core.base: [Job: 8] checking task_done number (0/4)...
-2022-05-09 15:53:51,128-INFO-apps.job.core.base: [Job: 8] check failed. task_done(0) less than task_num(4). end of close_job.
-2022-05-09 15:53:51,157-INFO-apps.job.core.base: [Job: 8] start to add job to queue...
-2022-05-09 15:53:51,314-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.start_server_job[7aab0a13-78e9-4b20-89c9-440cdde9f9d9] succeeded in 6.830189343076199s: None
-2022-05-09 15:54:29,781-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.handle_expired_job[0b7af22d-ee5b-440d-b220-41613957b1c8] received
-2022-05-09 15:54:29,785-INFO-celery.worker.strategy: Task apps.codeproj.tasks.base.handle_scheduled_projects[8be53386-05ea-4b85-86f5-65780d9d5be4] received
-2022-05-09 15:54:29,797-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询未关闭的超时任务，当前未关闭任务数: 0
-2022-05-09 15:54:29,804-INFO-apps.job.tasks.jobcheck: [PeriodicTasks] 开始查询未上报心跳的客户端任务: 0
-2022-05-09 15:54:29,809-INFO-apps.job.tasks.jobcheck: [PeriodicTasks]开始查询未确认的Task任务，当前未确认Task任务数: 0
-2022-05-09 15:54:29,826-INFO-celery.app.trace: Task apps.codeproj.tasks.base.handle_scheduled_projects[8be53386-05ea-4b85-86f5-65780d9d5be4] succeeded in 0.03704816591925919s: None
-2022-05-09 15:54:29,845-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.handle_expired_job[0b7af22d-ee5b-440d-b220-41613957b1c8] succeeded in 0.056789828930050135s: None
-2022-05-09 15:54:29,956-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_initing_job[e6af3a46-6fe2-4b9f-aa2e-f20ac591bd08] received
-2022-05-09 15:54:29,964-INFO-apps.job.tasks.jobcheck: 当前有0个任务初始化超时
-2022-05-09 15:54:29,988-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_initing_job[e6af3a46-6fe2-4b9f-aa2e-f20ac591bd08] succeeded in 0.029932181118056178s: None
-2022-05-09 15:55:30,794-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[7b22d20a-df62-4d60-929b-56a66edd69c2] received
-2022-05-09 15:55:30,828-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[7b22d20a-df62-4d60-929b-56a66edd69c2] succeeded in 0.031230906024575233s: None
-2022-05-09 15:58:30,879-INFO-celery.worker.strategy: Task apps.nodemgr.tasks.nodecheck.check_node_active[c6821f10-ee83-49c3-b0ca-98780de2a44d] received
-2022-05-09 15:58:30,909-INFO-celery.app.trace: Task apps.nodemgr.tasks.nodecheck.check_node_active[c6821f10-ee83-49c3-b0ca-98780de2a44d] succeeded in 0.02697177603840828s: None
-2022-05-09 15:59:30,021-INFO-celery.worker.strategy: Task apps.job.tasks.jobcheck.monitor_initing_job[1bd0e82f-d284-4492-89ad-933ed6b87b53] received
-2022-05-09 15:59:30,040-INFO-apps.job.tasks.jobcheck: 当前有0个任务初始化超时
-2022-05-09 15:59:30,132-INFO-celery.app.trace: Task apps.job.tasks.jobcheck.monitor_initing_job[1bd0e82f-d284-4492-89ad-933ed6b87b53] succeeded in 0.10586200514808297s: None
-2022-05-09 16:00:03,094-WARNING-celery.worker.consumer.consumer: consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.7/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.7/site-packages/kombu/transport/redis.py", line 957, in _brpop_read
    **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1192, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 800, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 320, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 251, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 197, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
-2022-05-09 16:00:03,105-WARNING-py.warnings: /usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

-2022-05-09 16:00:03,119-ERROR-celery.worker.consumer.consumer: consumer: Cannot connect to redis://redis:6379/1: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

-2022-05-09 16:00:05,132-INFO-celery.worker.consumer.connection: Connected to redis://redis:6379/1
-2022-05-09 16:00:05,145-INFO-celery.worker.consumer.mingle: mingle: searching for neighbors
-2022-05-09 16:00:06,160-INFO-celery.worker.consumer.mingle: mingle: all alone
