### ISSUE TITLE
进入到client目录下，执行命令：python3 codepuppy.py -l codepuppy.log start -t <token>报错

### ISSUE THREAD

**Issue by Hedyt** [Tencent/CodeAnalysis#443]
[root@BYVL-OPS-49-7 client]# python codepuppy.py -l codepuppy.log start -t 0712b895f30c5e958ec71a7c22e1b1a2ad1d5c6b
2022-07-05 18:19:20,061-INFO: Tencent Cloud Code Analysis (OpenSource Beta)
2022-07-05 18:19:20,067-INFO: /bin/sh: python3: command not found
Traceback (most recent call last):
  File "codepuppy.py", line 151, in <module>
    CodePuppy().main()
  File "codepuppy.py", line 45, in __init__
    raise ConfigError("python3 command(Python Version 3.7) is not available, please install first.")
util.exceptions.ConfigError: Error[204]: python3 command(Python Version 3.7) is not available, please install first.
[root@BYVL-OPS-49-7 client]# python --version
Python 3.7.12

**Comment by bensonhome** [comment]
@Hedyt 需要预装Python3.7，确保 python3 命令可用。你这里可以将python软链接到python3命令。

客户端文档：https://tencent.github.io/CodeAnalysis/zh/quickStarted/deployClient.html#%E9%80%9A%E8%BF%87%E6%BA%90%E4%BB%A3%E7%A0%81
