### ISSUE TITLE
使用 TCA-action 时提示“本地git代码属于游离态分支,请使用--branch参数指定分支名称”

### ISSUE THREAD

**Issue by w7849516230** [Tencent/CodeAnalysis#484]
在使用 TCA-action 时，把 tca.yml  中的触发条件改为 pull_request，提 PR 时执行报错，“本地git代码属于游离态分支,请使用--branch参数指定分支名称”，请问该在哪里配置呢？

触发条件配置：
```on:
  pull_request:
    branches:
      - main
```

报错信息：
```
****************************************************************************************************
代码分析结果: 
NodeError: Error[203]: 本地git代码属于游离态分支,请使用--branch参数指定分支名称.
****************************************************************************************************
2022-07-28 09:08:08,295-INFO: json report: /tca_action/lib/tca-client/scan_status.json
2022-07-28 09:08:08,295-ERROR: NodeError: Error[203]: 本地git代码属于游离态分支,请使用--branch参数指定分支名称.
Traceback (most recent call last):
  File "node/localtask/localrunner.py", line 345, in run
  File "node/localtask/localrunner.py", line 290, in __check_config_info
  File "node/localtask/localsrccheck.py", line 99, in check_local_source_dir
  File "node/localtask/localsrccheck.py", line [56](https://github.com/**/runs/7556753882?check_suite_focus=true#step:4:57), in get_scm_url
util.exceptions.NodeError: Error[203]: 本地git代码属于游离态分支,请使用--branch参数指定分支名称.
-2022-07-28 09:08:08,386-INFO: 
****************************************************************************************************
检查结果: 执行异常。
****************************************************************************************************
-2022-07-28 09:08:08,387-INFO: 结束.
-2022-07-28 09:08:08,387-WARNING: status code: 2
Error: Process completed with exit code 2.
```

**Comment by Lingghh** [comment]
感谢反馈，我们看下

**Comment by bensonhome** [comment]
@w7849516230 这里是用的完整模式跑的TCA-action吧？
pr触发时，checkout插件需要设置拉取pr源分支，否则会处于预合入的临死代码状态。
可以参考这里配置：https://github.com/TCATools/TCA-action/blob/main/doc/use-server.md

此外，完整模式需要确保GitHub工作流的执行环境，与自己搭建的tca server的网络是可连通的，最好使用自定义机器来跑github工作流。

使用默认的快速扫描模式，则不需要处理以上问题，可以参考快速扫描配置：https://github.com/TCATools/TCA-action
