### ISSUE TITLE
docker-compose部署，客户端无法连接server

### ISSUE THREAD

**Issue by wangsanshi123** [Tencent/CodeAnalysis#486]
版本：20220728.1
错误表现：一直卡在这里，且节点显示为失效
![image](https://user-images.githubusercontent.com/15081998/181490919-901f9903-b0bf-4263-8fb4-b703796dbc0d.png)
![1c1d7d61dad4ab1a95be67f2828ca8b](https://user-images.githubusercontent.com/15081998/181491378-54b6c7d6-d349-42bd-8b2a-5dc7c69aaa18.jpg)

相关日志：运行docker logs codeanalysis_client_1，显示如下日志

2022-07-28 18:37:52,122-ERROR: api request error: {"status_code":400,"code":1000,"msg":"节点处于不可用状态"}
url: http://nginx:8000/main/api/nodes/1/heartbeat/
2022-07-28 18:37:52,122-ERROR: method(heart_beat) call fails on error: HTTP Error 400: Bad Request
2022-07-28 18:37:52,122-INFO: retrying method(heart_beat) after 5 seconds
2022-07-28 18:37:57,137-ERROR: api request error: {"status_code":400,"code":1000,"msg":"节点处于不可用状态"}
url: http://nginx:8000/main/api/nodes/1/heartbeat/
2022-07-28 18:37:57,137-ERROR: method(heart_beat) call fails on error: HTTP Error 400: Bad Request
2022-07-28 18:37:57,137-INFO: retrying method(heart_beat) after 5 seconds
2022-07-28 18:38:02,150-ERROR: api request error: {"status_code":400,"code":1000,"msg":"节点处于不可用状态"}
url: http://nginx:8000/main/api/nodes/1/heartbeat/
2022-07-28 18:38:02,150-ERROR: method(heart_beat) call fails on error: HTTP Error 400: Bad Request
2022-07-28 18:38:02,150-INFO: retrying method(heart_beat) after 5 seconds
2022-07-28 18:38:07,170-INFO: method(heart_beat) call succeed after 1073 retries
2022-07-28 18:38:16,306-ERROR: task_params not exists or is null!
task_request: {
  "id": 1,
  "task_params": null,
  "taskprocessrelation_set": [
    {
      "id": 1,
      "process": "analyze",
      "priority": 1,
      "state": 4,
      "private": false,
      "create_time": "2022-07-28T17:13:05.207527+08:00",
      "start_time": "2022-07-28T18:38:07.232332+08:00",
      "end_time": null,
      "result_code": null,
      "result_msg": null,
      "result_url": null,
      "log_url": null,
      "task": 1,
      "node": 1
    },
    {
      "id": 2,
      "process": "datahandle",
      "priority": 2,
      "state": 4,
      "private": false,
      "create_time": "2022-07-28T17:13:05.230016+08:00",
      "start_time": "2022-07-28T18:38:07.232332+08:00",
      "end_time": null,
      "result_code": null,
      "result_msg": null,
      "result_url": null,
      "log_url": null,
      "task": 1,
      "node": 1
    }
  ],
  "tag": "Codedog_Linux",
  "task_version": "2.0",
  "module": "codelint",
  "task_name": "checkstyle",
  "private": false,
  "create_version": "2.0",
  "execute_version": null,
  "start_time": null,
  "end_time": null,
  "state": 0,
  "create_time": "2022-07-28T17:13:05.186722+08:00",
  "register_time": null,
  "log_url": null,
  "progress_rate": 0,
  "last_beat_time": "2022-07-28T17:13:05.186775+08:00",
  "job": 1,
  "execute_processes": [
    "analyze",
    "datahandle"
  ]
}
NoneType: None
2022-07-28 18:38:16,307-INFO: reset task_params to empty dict.
2022-07-28 18:38:16,307-INFO: node is free: True, get task: name=checkstyle, id=1, task_version=2.0
2022-07-28 18:38:16,385-INFO: clean data directory ...
2022-07-28 18:38:16,388-ERROR: task_params is wrong.
Traceback (most recent call last):
  File "/workspace/client/util/tooldisplay.py", line 28, in get_tool_display_name
    tool_params = task_request['task_params']['checktool']
KeyError: 'checktool'
2022-07-28 18:38:16,401-INFO: Python 3.7.12
2022-07-28 18:38:16,489-INFO: Task_1 (checkstyle) starts ...
2022-07-28 18:38:26,610-INFO: task checkstyle with id 1 is done
2022-07-28 18:38:26,611-INFO: uploading task(checkstyle) result(code:219) to server
2022-07-28 18:38:26,611-ERROR: method(update_task_progress) call fails on error: 'org_sid'
2022-07-28 18:38:26,611-ERROR: Update_task_progress fail. upload msg:上传结果
Traceback (most recent call last):
  File "/workspace/client/util/reporter.py", line 98, in update_task_progress
    info.percent)
  File "util/wrapper.py", line 28, in util.wrapper.__c__.__c__.__call__
  File "util/wrapper.py", line 63, in util.wrapper.__d__.__d__._call_method
  File "util/wrapper.py", line 65, in util.wrapper.__d__.__d__._call_method
  File "util/wrapper.py", line 92, in util.wrapper.__e__.__e__.__call__
  File "util/wrapper.py", line 154, in util.wrapper.__f__.__f__.__retry_call
  File "/workspace/client/util/api/dogserver.py", line 37, in __retry_on_error
    raise error
  File "util/wrapper.py", line 148, in util.wrapper.__f__.__f__.__retry_call
  File "/workspace/client/util/api/dogapi.py", line 75, in update_task_progress
    "jobs/%s/tasks/%s/progresses/" % (task_params["org_sid"],
KeyError: 'org_sid'
2022-07-28 18:38:26,612-ERROR: Fail to send result to file server! Error: project_id is empty(None), can't upload result to file server.
2022-07-28 18:38:26,612-ERROR: method(send_task_result) call fails on error: 'org_sid'
2022-07-28 18:38:26,612-INFO: retrying method(send_task_result) after 5 seconds
2022-07-28 18:38:31,617-ERROR: method(send_task_result) call fails on error: 'org_sid'
2022-07-28 18:38:31,617-INFO: retrying method(send_task_result) after 5 seconds
2022-07-28 18:38:36,622-ERROR: method(send_task_result) call fails on error: 'org_sid'
2022-07-28 18:38:36,622-INFO: retrying method(send_task_result) after 5 seconds
2022-07-28 18:38:41,624-ERROR: method(send_task_result) call fails on error: 'org_sid'
2022-07-28 18:38:41,625-INFO: retrying method(send_task_result) after 5 seconds

**Comment by Lingghh** [comment]
感谢反馈，我们看下

**Comment by Lingghh** [comment]
这里更新到版本20220728.1后，执行了哪些命令呢？
