### ISSUE TITLE
TCA-action 完整模式时 INPUT_BLOCK 不起作用

### ISSUE THREAD

**Issue by w7849516230** [Tencent/CodeAnalysis#492]
在使用 TCA-action 完整模式时，即使配置了 INPUT_BLOCK: true，当扫描发现问题时，也是显示通过的状态，请问该如何配置，让发现问题时提示失败？

tca.yml 配置：
```
env:
      INPUT_QUICK_SCAN: false
      INPUT_BLOCK: true
      INPUT_LABEL: safety
```

github action 执行日志：
```
2022-08-01 03:45:32,900-INFO: query result from server ...
2022-08-01 03:45:53,869-INFO: 
****************************************************************************************************
代码分析结果: 
[代码检查结果] 本次扫描发现新问题量: 1, 关闭问题量: 0
查看新增问题列表: http://xxx/t/KJl0Pc5C1yV/p/tca-test/code-analysis/repos/2/projects/4/codelint-issues?scan_open=11&state=1
查看所有问题列表: http://xxx/t/KJl0Pc5C1yV/p/tca-test/code-analysis/repos/2/projects/4/codelint-issues
任务执行详情: http://xxx/t/KJl0Pc5C1yV/p/tca-test/code-analysis/repos/2/projects/4/scan-history/11
****************************************************************************************************
2022-08-01 03:45:53,869-INFO: json report: /tca_action/lib/tca-client/scan_status.json
-2022-08-01 03:45:55,632-INFO: 
****************************************************************************************************
检查结果: 通过。
****************************************************************************************************
-2022-08-01 03:45:55,633-INFO: 结束.

**Comment by bensonhome** [comment]
@w7849516230 需要配置一下质量门禁指标，可以参考下最新的插件文档指引：https://github.com/TCATools/TCA-action/blob/main/doc/use-server.md

**Comment by w7849516230** [comment]
@bensonhome 按照新文档测试，发现 tca.yml 配置 INPUT_INCR_ERROR: 0 后，GitHub action 执行报错。
错误日志
```
2022-08-01 14:21:44,738-INFO: [文件数]过滤前：1，过滤后：1
2022-08-01 14:21:44,739-INFO: ['/tca_action/lib/tools/linux-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/tca_action/lib/tca-client/data/taskdirs/task_46/scc_result_453f152a11a511edabad0242ac120002.json', '/__w/TCAJavaSimpleTest/TCAJavaSimpleTest']
2022-08-01 14:21:44,824-INFO: results written to /tca_action/lib/tca-client/data/taskdirs/task_46/scc_result_453f152a11a511edabad0242ac120002.json
2022-08-01 14:21:53,758-INFO: Task_47 is done.
2022-08-01 14:21:56,097-INFO: Task_48 (CheckStyle) starts ...
2022-08-01 14:21:56,198-INFO: Task_46 is done.
2022-08-01 14:21:58,311-ERROR: 任务(Semgrep)扫描失败: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /tca_action/lib/tools/custom-semgrep/result.json
请查看本地日志文件(/tca_action/lib/tca-client/data/taskdirs/task_46_1/task.log),
或前往 http://xxxx/t/KJl0Pc5C1yV/p/tca-test/code-analysis/repos/2/projects/7/scan-history/14 (点击异常子任务->下载进程日志)查看失败原因.
2022-08-01 14:21:58,312-INFO: Get code line data...
2022-08-01 14:21:58,312-INFO: 本次分析代码行数: 35
2022-08-01 14:21:58,312-INFO: 全量代码行数: [102](https://github.com/w7849516230/TCAJavaSimpleTest/runs/7613285790?check_suite_focus=true#step:4:103)
2022-08-01 14:22:01,995-INFO: 
****************************************************************************************************
代码分析结果: 
任务(Semgrep)扫描失败: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /tca_action/lib/tools/custom-semgrep/result.json
请查看本地日志文件(/tca_action/lib/tca-client/data/taskdirs/task_46_1/task.log),
或前往 http://xxx.[105](https://github.com/w7849516230/TCAJavaSimpleTest/runs/7613285790?check_suite_focus=true#step:4:106)/t/KJl0Pc5C1yV/p/tca-test/code-analysis/repos/2/projects/7/scan-history/14 (点击异常子任务->下载进程日志)查看失败原因.
****************************************************************************************************
2022-08-01 14:22:01,995-INFO: json report: /tca_action/lib/tca-client/scan_status.json
-2022-08-01 14:22:03,278-INFO: 
****************************************************************************************************
检查结果: 执行异常。
****************************************************************************************************
-2022-08-01 14:22:03,278-INFO: 结束.
-2022-08-01 14:22:03,278-WARNING: status code: 2
Error: Process completed with exit code 2.
```

如果删除 INPUT_INCR_ERROR: 0，执行不会报错。

**Comment by w7849516230** [comment]
又测试了下，发现 tca.yml 配置中加入 INPUT_SCHEME_ID: 8 就会导致 GitHub action 执行异常。删除后，即使配置类似 INPUT_TOTAL_INFO 也会成功。

**Comment by bensonhome** [comment]
@w7849516230 这里报错是Semgrep工具执行异常，可以按照提示的页面链接里，下载日志看下报错是什么

**Comment by w7849516230** [comment]
执行结果：节点端本地扫描错误 task[46] TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /tca_action/lib/tools/custom-semgrep/result.json

执行日志：
```
2022-08-01 14:21:45,285-INFO: start to run task: Semgrep, execute_processes: ['analyze', 'datahandle']
2022-08-01 14:21:45,781-WARNING: 不是内置工具,使用自定义工具模块(No module named 'tool.semgrep')
2022-08-01 14:21:45,782-INFO: task start : <class 'task.model.analyze.AnalyzeTask'>
2022-08-01 14:21:45,782-INFO: pre_analyze start.
2022-08-01 14:21:45,782-INFO: start __checkout_source_dir.
2022-08-01 14:21:45,782-INFO: 本地项目，直接复用传入的source_dir.
2022-08-01 14:21:45,782-INFO: load_source_dir done. source_dir insert env. sourcedir: /__w/TCAJavaSimpleTest/TCAJavaSimpleTest
2022-08-01 14:21:45,782-INFO: pre_analyze done.
2022-08-01 14:21:45,782-INFO: PATH =
****************************************************************************************************
/tca_action/lib/tools/linux-node-v12.16.3/bin
/tca_action/lib/tools/common-dart-code-metrics-1.7.1/bin
/tca_action/lib/tools/linux-dart-sdk-v2.7.2/bin
/tca_action/lib/tools/linux-jdk1.8.0_65/bin
/tca_action/lib/tools/linux-git-lfs-v3.1.2
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
****************************************************************************************************
2022-08-01 14:21:45,984-INFO: Current branch(test_scan) latest revision: da837e75e4f95f4c6e26581cb51ae41da4ea6836
2022-08-01 14:21:45,984-INFO: Get base revision between test_scan and main: d6e839343c4cd518c706d77f26103c9aa41eb609
2022-08-01 14:21:46,387-INFO: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
2022-08-01 14:21:46,388-INFO: Codelint only cans main code.
2022-08-01 14:21:47,886-INFO: Load from git to /tca_action/lib/tools/custom-semgrep ...
2022-08-01 14:21:49,437-INFO: 正在设置CodeDog内置Python环境(PYTHON37_HOME)...
2022-08-01 14:21:49,442-INFO: Python 3.7.2
2022-08-01 14:21:49,538-INFO: 获取需要扫描的文件
2022-08-01 14:21:49,538-INFO: getting scm diff filepaths
2022-08-01 14:21:49,639-INFO: get diff files(vs. origin/main) ...
2022-08-01 14:21:49,740-INFO: diff files(vs. origin/main): [DiffPath(path='.github/workflows/tca.yml', state='mod'), DiffPath(path='src/main/java/Main.java', state='mod')]
2022-08-01 14:21:49,740-INFO: diff files (vs. last revision): [DiffPath(path='.github/workflows/tca.yml', state='mod')]
2022-08-01 14:21:49,740-INFO: diff files (vs. compared branch && last revision): [DiffPath(path='.github/workflows/tca.yml', state='mod')]
2022-08-01 14:21:49,740-INFO: finish getting scm diff filepaths
2022-08-01 14:21:49,748-INFO: [文件数]过滤前：1，过滤后：1
2022-08-01 14:21:49,850-INFO: use SubProcController run cmd: python main.py
2022-08-01 14:21:53,904-INFO: Traceback (most recent call last):
2022-08-01 14:21:53,904-INFO:   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-08-01 14:21:53,904-INFO:     "__main__", mod_spec)
2022-08-01 14:21:53,904-INFO:   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
2022-08-01 14:21:53,904-INFO:     exec(code, run_globals)
2022-08-01 14:21:53,904-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/__main__.py", line 5, in <module>
2022-08-01 14:21:53,904-INFO:     from semgrep.cli import cli
2022-08-01 14:21:53,904-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/cli.py", line 6, in <module>
2022-08-01 14:21:53,904-INFO:     import semgrep.config_resolver
2022-08-01 14:21:53,904-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/config_resolver.py", line 24, in <module>
2022-08-01 14:21:53,904-INFO:     from semgrep.error import InvalidRuleSchemaError
2022-08-01 14:21:53,904-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/error.py", line 16, in <module>
2022-08-01 14:21:53,904-INFO:     from semgrep.util import with_color
2022-08-01 14:21:53,905-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/util.py", line 209, in <module>
2022-08-01 14:21:53,905-INFO:     SEMGREP_PATH = compute_semgrep_path()
2022-08-01 14:21:53,905-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/util.py", line 202, in compute_semgrep_path
2022-08-01 14:21:53,905-INFO:     return compute_executable_path("semgrep-core")
2022-08-01 14:21:53,905-INFO:   File "/usr/local/lib/python3.7/site-packages/semgrep/util.py", line 184, in compute_executable_path
2022-08-01 14:21:53,905-INFO:     pkg_exec = pkg_resources.resource_filename("semgrep.bin", exec_name)
2022-08-01 14:21:53,905-INFO: AttributeError: module 'pkg_resources' has no attribute 'resource_filename'
2022-08-01 14:21:53,919-INFO: -- start run tool ...
2022-08-01 14:21:53,920-INFO: [debug] source_dir: /__w/TCAJavaSimpleTest/TCAJavaSimpleTest
2022-08-01 14:21:53,920-INFO: [debug] envs:  
2022-08-01 14:21:53,920-INFO: 
2022-08-01 14:21:53,920-INFO: [debug] PATH: /tca_action/lib/tools/linux-node-v12.16.3/bin:/tca_action/lib/tools/common-dart-code-metrics-1.7.1/bin:/tca_action/lib/tools/linux-dart-sdk-v2.7.2/bin:/tca_action/lib/tools/linux-jdk1.8.0_65/bin:/tca_action/lib/tools/linux-git-lfs-v3.1.2:/tca_action/lib/tools/linux-node-v12.16.3/bin:/tca_action/lib/tools/common-dart-code-metrics-1.7.1/bin:/tca_action/lib/tools/linux-dart-sdk-v2.7.2/bin:/tca_action/lib/tools/linux-jdk1.8.0_65/bin:/tca_action/lib/tools/linux-git-lfs-v3.1.2:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2022-08-01 14:21:53,920-INFO: get diff file: /tca_action/lib/tca-client/data/taskdirs/task_46_1/diff_files.json
2022-08-01 14:21:53,920-INFO: [debug] cmd: python3 -m semgrep --config /tca_action/lib/tools/custom-semgrep/config_rules --dangerously-allow-arbitrary-code-execution-from-rules --no-git-ignore --json --output error_output.json /__w/TCAJavaSimpleTest/TCAJavaSimpleTest/.github/workflows/tca.yml
2022-08-01 14:21:53,920-INFO: Traceback (most recent call last):
2022-08-01 14:21:53,920-INFO:   File "main.py", line 178, in <module>
2022-08-01 14:21:53,920-INFO:     Semgrep().run()
2022-08-01 14:21:53,920-INFO:   File "main.py", line 141, in run
2022-08-01 14:21:53,920-INFO:     subprocess.check_output(cmd)
2022-08-01 14:21:53,920-INFO:   File "/tca_action/lib/tools/linux-Python-v3.7.2/lib/python3.7/subprocess.py", line 395, in check_output
2022-08-01 14:21:53,920-INFO:     **kwargs).stdout
2022-08-01 14:21:53,920-INFO:   File "/tca_action/lib/tools/linux-Python-v3.7.2/lib/python3.7/subprocess.py", line 487, in run
2022-08-01 14:21:53,921-INFO:     output=stdout, stderr=stderr)
2022-08-01 14:21:53,921-INFO: subprocess.CalledProcessError: Command '['python3', '-m', 'semgrep', '--config', '/tca_action/lib/tools/custom-semgrep/config_rules', '--dangerously-allow-arbitrary-code-execution-from-rules', '--no-git-ignore', '--json', '--output', 'error_output.json', '/__w/TCAJavaSimpleTest/TCAJavaSimpleTest/.github/workflows/tca.yml']' returned non-zero exit status 1.
2022-08-01 14:21:53,929-WARNING: task status code is 226
2022-08-01 14:21:53,929-WARNING: task messsage: TaskError: Error[226]: 第三方工具执行异常,未生成结果文件: /tca_action/lib/tools/custom-semgrep/result.json
2022-08-01 14:21:53,929-INFO: task result: /tca_action/lib/tca-client/data/taskdirs/task_46_1/task_response.json
```

**Comment by bensonhome** [comment]
@w7849516230 是Semgrep打包镜像问题，已经修复了，可以重新跑一下试试。

**Comment by w7849516230** [comment]
@bensonhome 目前是能正常运行了，但是扫描不出问题了，我是不是得重新开个 issue 了。
