### ISSUE TITLE
配置用户凭证拉取github代码库帐号无权限 没人回答了吗？

### ISSUE THREAD

**Issue by michael1981** [Tencent/CodeAnalysis#58]
![image](https://user-images.githubusercontent.com/23006690/148744840-37884572-7cb9-486d-b482-089269db60f9.png)

**Comment by Lingghh** [comment]
github拉取代码需要用"personal access token"

**Comment by michael1981** [comment]
> github拉取代码需要用"personal access token"

拉取我知道怎么填，在咱们仓库登记里怎么填写呢？

**Comment by Lingghh** [comment]
直接作为``password``填入即可

**Comment by michael1981** [comment]
> 直接作为`password`填入即可

还是不行，需要说明具体怎么在仓库里增加代码库操作。

**Comment by michael1981** [comment]
还有人回答没有？

**Comment by Lingghh** [comment]
> ![image](https://user-images.githubusercontent.com/23006690/148744840-37884572-7cb9-486d-b482-089269db60f9.png)

在这个页面就可以登记代码库哈
然后点击”新增凭证“之后会跳到新页面添加凭证，然后回到这个页面点击“重新拉取凭证”，即可完成登记

你获取了``access token``可以在本地结合用户名clone一下试试，看是否ok
如果本地可以但在TCA平台上不可以，可以看一下``logs/scmproxy.log``日志看一下输出的报错原因

> 查看日志的方式：
> Docker-Compose部署：``docker-compose exec scmproxy /bin/bash``、``tail -n 100 logs/scmproxy.log``
> 本地部署：``cd server/projects/scmproxy && tail -n 100 logs/scmproxy.log``

**Comment by michael1981** [comment]
我在新增凭证 里填的就是github的用户名和token，就是提示的错误或者没有权限

**Comment by michael1981** [comment]
2022-01-13 09:53:47,738 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 09:53:47,826 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 10:53:47,839 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 10:53:47,927 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 11:53:47,941 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 11:53:48,024 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 12:53:48,036 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 12:53:48,111 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 13:53:48,120 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 13:53:48,208 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 14:53:48,213 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 14:53:48,279 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 15:53:48,300 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 15:53:48,379 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 16:53:48,379 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source
2022-01-13 16:53:48,476 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/sourcedirs to remove overdue source
2022-01-13 17:53:48,477 PID:1 sourcemgr.py-line:35 | INFO - Traverse directory at /var/www/django/codedog/.proxy_temp to remove overdue source

**Comment by Lingghh** [comment]
麻烦在代码库登记页面填写好信息后，点击”确认“，然后看一下``main-server``的日志
```
docker-compose exec main-server /bin/bash

tail -n 100 log/codedog.log
```

**Comment by purple-force** [comment]
codeanalysis_scmproxy 容器起不来，导致登记代码库时，报错cd_error 代码库及帐号不匹配。
![image](https://user-images.githubusercontent.com/16146970/149772582-1f539600-ede9-46ec-849c-f261be78f3b3.png)

![image](https://user-images.githubusercontent.com/16146970/149772622-a659725b-0a0a-4156-8771-3d1d266811b5.png)


Traceback (most recent call last):

  File "proxyserver.py", line 20, in <module>

    import apis

  File "/var/www/django/codedog/apis.py", line 20, in <module>

    from lib.cmdscm import ScmClient

  File "/var/www/django/codedog/lib/cmdscm.py", line 13, in <module>

    from lib._cmdgit import CmdGit

ModuleNotFoundError: No module named 'lib._cmdgit'

Traceback (most recent call last):

  File "proxyserver.py", line 20, in <module>

    import apis

  File "/var/www/django/codedog/apis.py", line 20, in <module>

    from lib.cmdscm import ScmClient

  File "/var/www/django/codedog/lib/cmdscm.py", line 13, in <module>

    from lib._cmdgit import CmdGit

ModuleNotFoundError: No module named 'lib._cmdgit'

Traceback (most recent call last):

  File "proxyserver.py", line 20, in <module>

    import apis

  File "/var/www/django/codedog/apis.py", line 20, in <module>

    from lib.cmdscm import ScmClient

  File "/var/www/django/codedog/lib/cmdscm.py", line 13, in <module>

    from lib._cmdgit import CmdGit

ModuleNotFoundError: No module named 'lib._cmdgit'

**Comment by Lingghh** [comment]
@purple-force 这里应该是M1架构问题
可以将``server/dockerconfs/Dockerfile-common``的基础镜像调整为``amd64/python:3.7.12-slim``试试

**Comment by michael1981** [comment]
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/django/codedog/apps/codeproj/serializers/v3.py", line 172, in validate
    scm_client.auth_check()
  File "/var/www/django/codedog/util/errorcatch.py", line 46, in _callwrap
    rst = self._err_handler(err)
  File "/var/www/django/codedog/util/scm/base.py", line 247, in git_error_handler
    raise error_type
util.scm.base.ScmConnectionError: 获取代码信息耗时较久，请稍后再试
-2022-01-24 09:20:25,057-WARNING-util.handlers: exception response: {'cd_error': [ErrorDetail(string='代码库及帐号不匹配', code='invalid')]}
-2022-01-24 09:20:25,057-INFO-util.handlers: custom error response data: {'status_code': 400, 'code': 1000, 'msg': 'cd_error 代码库及帐号不匹配', 'invalid_fields': [{'field': 'cd_error', 'message': [ErrorDetail(string='代码库及帐号不匹配', code='invalid')]}]}
-2022-01-24 09:20:25,058-WARNING-django.request: Bad Request: /api/v3/orgs/KpgJdBZks7O/teams/cticloud/repos/
-2022-01-24 09:28:11,969-ERROR-apps.codeproj.core.projmgr: create repo exception: (1062, "Duplicate entry 'http://github.com/*********' for key 'codeproj_baserepository_scm_url_url_key_*******_uniq'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry 'http://github.com/*******' for key 'codeproj_baserepository_scm_url_url_key_********_uniq'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/django/codedog/apps/codeproj/core/projmgr.py", line 127, in v3_create_repo
    scm_type=scm_type, scm_url=scm_url, user=user, url_key=url_key, project_team=pt)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/django/codedog/apps/base/basemodel.py", line 145, in create
    return super(MTQuerySet, self).create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/django/codedog/apps/base/basemodel.py", line 257, in save
    return super(CDBaseModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.7/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.7/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.7/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'http://github.com/**********' for key 'codeproj_baserepository_scm_url_url_key*********'")
-2022-01-24 09:28:11,974-WARNING-util.handlers: exception response: {'code': 1040, 'msg': '代码库已接入'}
-2022-01-24 09:28:11,974-INFO-util.handlers: custom error response data: {'status_code': 400, 'code': 1040, 'msg': '代码库已接入'}
-2022-01-24 09:28:11,975-WARNING-django.request: Bad Request: /api/v3/orgs/KpgJdBZks7O/teams/cticloud/repos/
root@1ddd92f125af:/var/www/django/codedog#

**Comment by michael1981** [comment]
这个是怎么回事呢？

**Comment by Lingghh** [comment]
这里看日志，应该是代码库重复登记了。
实际使用中，该代码库是否登记成功了呢？当前部署机器能否访问GitHub呢？

**Comment by michael1981** [comment]
库里虽然是已经添加成功了，不过其实是不成功的，拉取也不可以，一直提示代码库及帐号不匹配。

**Comment by Lingghh** [comment]
麻烦在``scmproxy``容器内执行以下命令，手动拉取一下代码试试，看看是否能够拉成功，如果不能，可能是网络问题。

```bash
docker-compose exec scmproxy /bin/bash

# xxx/xxx 表示具体的代码库地址
git clone https://github.com/xxx/xxx
```

**Comment by Lingghh** [comment]
@michael1981 目前在机器的容器内可以正常拉取github代码库吗

**Comment by michael1981** [comment]
需要通过personal access token才可以，之前应该是环境问题。
