### ISSUE TITLE
ERROR: TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by pengpengdai** [Tencent/CodeAnalysis#617]
本地启动分析报错

命令
./codepuppy localscan -t xxxxx -s /Users/huolala/Documents/Jenkins/workspace/app-ios-tlzo4peh-prd4vvk7/binary/source --org-sid xxxx --team-name xxxx-ios --scan-plan default --branch release --build-cmd xcodebuild --report report.json --server http://xxxx/server/main/ --start-type CI

异常日志
2022-09-14 09:37:52,453-INFO: Tencent Cloud Code Analysis (OpenSource Beta)
2022-09-14 09:37:52,453-INFO: running in a PyInstaller bundle
2022-09-14 09:37:52,506-INFO: ------------------------------
2022-09-14 09:37:52,507-INFO:  #######    ####      # 
2022-09-14 09:37:52,507-INFO:     #      #    #     # 
2022-09-14 09:37:52,507-INFO:     #     #          ### 
2022-09-14 09:37:52,507-INFO:     #     #          # # 
2022-09-14 09:37:52,507-INFO:     #     #         #####
2022-09-14 09:37:52,507-INFO:     #      #    #   #   #
2022-09-14 09:37:52,507-INFO:     #       ####   ##   ##
2022-09-14 09:37:52,507-INFO: ------------------------------
2022-09-14 09:37:56,974-INFO: using config file: /Users/huolala/Documents/JKS/TCA/tca-client-v20220819.1-x86_64-apple-darwin/codedog.ini
2022-09-14 09:37:56,976-INFO: connect to server: http://xxxx/
2022-09-14 09:37:57,846-INFO: scan plan(default) already exists: http://xxxxxx/t/xxxx/p/xxxx-ios/code-analysis/repos/6/schemes/5/basic
2022-09-14 09:37:57,889-INFO: Use the already existed project(id: 3).
2022-09-14 09:37:58,474-INFO: Project url: http://xxxxxxx/t/xxxx/p/driver-ios/code-analysis/repos/6/projects/3/overview
2022-09-14 09:37:59,289-INFO: Job starts ...
2022-09-14 09:38:02,684-INFO: Load tool config: https://github.com/TCATools/puppy-tools-config.git
2022-09-14 09:38:04,836-INFO: Initing common tools ...
2022-09-14 09:38:04,836-INFO: Initing 3 tools, please wait a minute ...
[Tools init]: 100%|███████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.40it/s]
2022-09-14 09:38:07,516-INFO: Initialize tools done.(use time: 2.68s)
2022-09-14 09:38:07,540-INFO: run cmd: git lfs install
2022-09-14 09:38:07,641-INFO: Git LFS initialized.
2022-09-14 09:38:07,651-INFO: Initing other tools ...
2022-09-14 09:38:07,656-INFO: Initing 12 tools, please wait a minute ...
[Tools init]: 100%|█████████████████████████████████████████████████| 12/12 [00:04<00:00,  3.00it/s]
2022-09-14 09:38:11,661-INFO: Initialize tools done.(use time: 4.00s)
2022-09-14 09:38:11,665-INFO: 
****************************************************************************************************
代码分析结果: 
TypeError: expected str, bytes or os.PathLike object, not NoneType
****************************************************************************************************
2022-09-14 09:38:11,666-INFO: json report: /Users/huolala/Documents/JKS/TCA/tca-client-v20220819.1-x86_64-apple-darwin/report.json
2022-09-14 09:38:11,666-ERROR: TypeError: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "node/localtask/localrunner.py", line 386, in run
  File "node/localtask/requestgenerator.py", line 158, in generate_request
  File "node/localtask/requestgenerator.py", line 185, in _get_execute_request_list
  File "node/localtask/taskprocessmgr.py", line 75, in get_supported_processes
  File "task/taskmgr.py", line 118, in check_tool_usable
  File "tool/collie.py", line 37, in check_tool_usable
  File "tool/util/collie.py", line 65, in get_cmd
  File "posixpath.py", line 80, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by cyw3** [comment]
独立工具暂不开放Mac版本。

可以给TCA挂载一两台linux在线节点。这样Mac下不支持的工具，在localscan模式执行时候会自动判断是否能够执行，不能的话会自动发送到在线节点上去执行
