### ISSUE TITLE
使用docker-compose本地部署main分支代码，登录接口报错

### ISSUE THREAD

**Issue by purple-force** [Tencent/CodeAnalysis#62]
![image](https://user-images.githubusercontent.com/16146970/148895953-b1e07cad-2e42-4f3a-9399-dc9c0240f887.png)

**Comment by RussGan** [comment]
可以执行下./compose_init.sh脚本再试试哈

**Comment by purple-force** [comment]
不行唉

**Comment by Lingghh** [comment]
这里不行是指执行``./compose_init.sh``脚本之后登录还是会报错么

**Comment by purple-force** [comment]
是的.

Environment:


Request Method: GET
Request URL: http://0.0.0.0/api/v3/login/get_oapassword_info/

Django Version: 3.1.12
Python Version: 3.7.12
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'login']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'login.middleware.loginmiddleware.ResponseMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/utils/deprecation.py", line 116, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python3.7/site-packages/django/middleware/common.py", line 113, in process_response
    response['Content-Length'] = str(len(response.content))
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 127, in content
    'The response content must be rendered before it can be accessed.'

Exception Type: ContentNotRenderedError at /api/v3/login/get_oapassword_info/
Exception Value: The response content must be rendered before it can be accessed.

**Comment by Lingghh** [comment]
这里可以执行一下以下命令，然后再访问试试
```
docker-compose exec login-server /bin/bash

python manage.py createcachetable
```

**Comment by purple-force** [comment]
docker-compose exec login-server /bin/bash
root@e555655eb737:/var/www/django/codedog# python manage.py createcachetable
-2022-01-12 02:20:32,305-DEBUG-asyncio: Using selector: EpollSelector
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 614, in connect
    (self.host, self.port), self.connect_timeout, **kwargs
  File "/usr/local/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno -2] Name or service not known)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    main()
  File "manage.py", line 24, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/createcachetable.py", line 43, in handle
    self.create_table(db, cache._table, dry_run)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/createcachetable.py", line 51, in create_table
    if tablename in connection.introspection.table_names():
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/introspection.py", line 46, in table_names
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/pymysql/connections.py", line 664, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno -2] Name or service not known)")


看有报错是mysql连不上。我的机器是M1的，默认的mysql版本是5.7.24，似乎不支持M1，换了8.0.27，最新版，还是有报错。
![image](https://user-images.githubusercontent.com/16146970/149053180-7c35068a-e31b-4ff7-92d7-3ba93defcdb0.png)


Pulling mysql (mysql:8.0.27)...
8.0.27: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

**Comment by Lingghh** [comment]
看起来是mysql服务没有启动，我们这边用M1机器测试一下

**Comment by Lingghh** [comment]
这里可以将 ``mysql:8.0.27`` 调整为 ``mariadb:10.5.8``试试

**Comment by purple-force** [comment]
可以了

**Comment by FanLu1994** [comment]
> 这里可以执行一下以下命令，然后再访问试试
> 
> ```
> docker-compose exec login-server /bin/bash
> 
> python manage.py createcachetable
> ```

win11执行这个之后，登录报400，密码错误怎么办呢？ 有预留注册接口吗
