### ISSUE TITLE
upload_file windows环境报错

### ISSUE THREAD

**Issue by Grapefruit-Shu** [Tencent/CodeAnalysis#66]
========================================================================
2022-01-11 15:33:50,366-INFO-util.logutil: Task_89 (Flake8) starts ...
2022-01-11 15:34:00,491-INFO-util.logutil: Task_89 is done.
2022-01-11 15:34:00,998-ERROR-util.wrapper: method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)
2022-01-11 15:34:00,999-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
2022-01-11 15:34:06,009-ERROR-util.wrapper: method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)
2022-01-11 15:34:06,009-INFO-util.wrapper: retrying method(upload_file) after 5 seconds
2022-01-11 15:34:11,021-ERROR-util.wrapper: method(upload_file) call fails on error: Expecting value: line 1 column 1 (char 0)
2022-01-11 15:34:11,022-WARNING-util.wrapper: method(upload_file) call still fails after 2 retries

2022-01-11 15:34:11,025-ERROR-util.logutil: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "H:\CodeAnalysis-main\client\node\localrunner.py", line 392, in run
    run_task_mgr.scan_project(cur_execute_request_list, proj_conf)
  File "H:\CodeAnalysis-main\client\node\localtask\runlocaltask.py", line 96, in scan_project
    self._proj_id).run()
  File "H:\CodeAnalysis-main\client\node\localtask\runtask.py", line 170, in run
    ResultCheck.upload_task_result(task, self._proj_id)
  File "H:\CodeAnalysis-main\client\node\localtask\runtask.py", line 97, in upload_task_result
    data_url, log_url = TaskRunner.upload_result_detail(proj_id, task.task_id, task_dir, data, task.task_log)
  File "node\taskrunner.py", line 59, in node.taskrunner.TaskRunner.upload_result_detail
  File "util\wrapper.py", line 51, in util.wrapper._RetryMethod.__call__
  File "util\wrapper.py", line 107, in util.wrapper.Retry.__retry_call
  File "util\wrapper.py", line 92, in util.wrapper.Retry.__retry_call
  File "H:\CodeAnalysis-main\client\util\api\fileserver.py", line 103, in upload_file
    return self.__upload_data(fp, rel_url, headers)
  File "H:\CodeAnalysis-main\client\util\api\fileserver.py", line 87, in __upload_data
    HttpClient(self._server_url, rel_url, headers=headers, data=data, proxies=self._proxies).put()
  File "H:\CodeAnalysis-main\client\util\api\httpclient.py", line 82, in put
    result = HttpRequest.request(url=self.url, headers=self.headers, body=self.data, method="PUT")
  File "H:\CodeAnalysis-main\client\util\api\httpclient.py", line 45, in request
    dict_result = json.loads(str_result)
  File "C:\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
====================================================================

下载的main分支的代码，最后结果上传的时候报错了

**Comment by Lingghh** [comment]
本地client的``config.ini``有配置FILE_SERVER的url和token么

**Comment by Grapefruit-Shu** [comment]
这个填了的
; [必填]文件服务器地址，请将<Server IP地址>替换为实际的tca server地址
URL=http://10.11.66.69:8000/server/files/
; [必填]文件服务器token
TOKEN=0712b895f30c5e958ec71a7c22e1b1a2ad1d5c6b

token是我在个人中心那个 token中copy的

**Comment by Lingghh** [comment]
平台页面访问入口是通过8000端口还是80端口呢？

**Comment by Grapefruit-Shu** [comment]
平台页面是通过80端口访问的

**Comment by Grapefruit-Shu** [comment]
换成80端口就可以了，8000 为TCA Server访问端口这个是干啥用的

**Comment by Lingghh** [comment]
这个是后端服务监听的端口
