### ISSUE TITLE
CLS增强版扫描报错，申请license配置好后，扫描不成功

### ISSUE THREAD

**Issue by jklZy1** [Tencent/CodeAnalysis#670]
报错任务日志：
2022-10-25 10:59:33,981-INFO: start to run task: TCA-Armory-C2, execute_processes: ['analyze', 'datahandle']
2022-10-25 10:59:34,118-ERROR: api request error: {"status":400,"msg":"License Not Found"}
url: http://172.17.18.113/communicate/key
2022-10-25 10:59:34,124-ERROR: method(post) call fails on error: HTTP Error 400: Bad Request
2022-10-25 10:59:34,124-INFO: retrying method(post) after 30 seconds
2022-10-25 11:00:04,207-ERROR: api request error: {"status":400,"msg":"License Not Found"}
url: http://172.17.18.113/communicate/key
2022-10-25 11:00:04,207-ERROR: method(post) call fails on error: HTTP Error 400: Bad Request
2022-10-25 11:00:04,207-INFO: retrying method(post) after 30 seconds
2022-10-25 11:00:34,271-ERROR: api request error: {"status":400,"msg":"License Not Found"}
url: http://172.17.18.113/communicate/key
2022-10-25 11:00:34,271-ERROR: method(post) call fails on error: HTTP Error 400: Bad Request
2022-10-25 11:00:34,271-WARNING: method(post) call still fails after 2 retries
2022-10-25 11:00:34,284-WARNING: task status code is 204
2022-10-25 11:00:34,285-WARNING: task messsage: TaskError: Error[204]: License check failed! Please check the license. HTTP Error 400: Bad Request
2022-10-25 11:00:34,285-WARNING: task result: 
Traceback (most recent call last):
  File "task/puppytask.py", line 63, in run
    response = TaskRunner(self._request_file, self._response_file).run_task()
  File "task/runtask.py", line 80, in task.runtask.__tskr__.__tskr__.run_task
util.exceptions.TaskError: Error[204]: License check failed! Please check the license. HTTP Error 400: Bad Request

2022-10-25 11:00:34,286-INFO: task result: /opt/app/CodeAnalysis/client/data/taskdirs/task_777/task_response.json

**Comment by cyw3** [comment]
可以用以下命令看看CLS是否成功部署起来：
```bash
ps aux|grep cls
```

**Comment by jklZy1** [comment]
> 可以用以下命令看看CLS是否成功部署起来：
> 
> ```shell
> ps aux|grep cls
> ```

已经部署成功了，进程和端口都在的；但是扫描的时候一直报错，api调用异常

**Comment by cyw3** [comment]
TCA Client中的 config.ini 文件中的 `License` 字段是否配置的是 CLS 生成的 Client License呢？

**Comment by jklZy1** [comment]
> TCA Client中的 config.ini 文件中的 `License` 字段是否配置的是 CLS 生成的 Client License呢？

是的；在config.ini配置的是第一次执行./cls server 命令，生成的 client license，我做了备份；
这个值为什么只有第一次执行的时候才会生成，后面再执行就不生成了

**Comment by cyw3** [comment]
好的

麻烦在开源群中激活下，我到时候私聊你看看

**Comment by cyw3** [comment]
经过排查，是由于Client License配置错误，不是完整的Client License。目前已解决。
