### ISSUE TITLE
win10使用客户端扫描启动报错

### ISSUE THREAD

**Issue by 980468094** [Tencent/CodeAnalysis#767]
ip在浏览器中可以正常使用，也可以ping的通，但是使用client启动时一直报这个问题

2023-02-14 18:26:39,793-INFO: Tencent Cloud Code Analysis (OpenSource Beta)
2023-02-14 18:26:39,819-INFO: Python 3.7.0
2023-02-14 18:26:39,963-INFO: ------------------------------
2023-02-14 18:26:39,963-INFO:  #######    ####      # 
2023-02-14 18:26:39,963-INFO:     #      #    #     # 
2023-02-14 18:26:39,963-INFO:     #     #          ### 
2023-02-14 18:26:39,964-INFO:     #     #          # # 
2023-02-14 18:26:39,964-INFO:     #     #         #####
2023-02-14 18:26:39,964-INFO:     #      #    #   #   #
2023-02-14 18:26:39,964-INFO:     #       ####   ##   ##
2023-02-14 18:26:39,964-INFO: ------------------------------
2023-02-14 18:26:40,010-INFO: using config file: F:\Users\Administrator\Desktop\工作内容\716\CHM\client\codedog.ini
2023-02-14 18:26:40,011-INFO: connect to server: http://192.168.31.10/
2023-02-14 18:26:50,384-ERROR: method(is_repo_existed) call fails on error: Expecting value: line 1 column 1 (char 0)
2023-02-14 18:26:50,385-INFO: retrying method(is_repo_existed) after 5 seconds
2023-02-14 18:27:04,391-ERROR: method(is_repo_existed) call fails on error: Expecting value: line 1 column 1 (char 0)
2023-02-14 18:27:04,391-INFO: retrying method(is_repo_existed) after 5 seconds
2023-02-14 18:27:18,396-ERROR: method(is_repo_existed) call fails on error: Expecting value: line 1 column 1 (char 0)
2023-02-14 18:27:18,396-WARNING: method(is_repo_existed) call still fails after 2 retries
2023-02-14 18:27:18,397-INFO: 
****************************************************************************************************
代码分析结果: 
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
****************************************************************************************************
2023-02-14 18:27:18,397-INFO: json report: F:/Users/Administrator/Desktop/工作内容/716/CHM/client/scan_status.json
2023-02-14 18:27:18,397-ERROR: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "F:\Users\Administrator\Desktop\工作内容\716\CHM\client\node\localtask\localrunner.py", line 378, in run
    self._repo_id, self._proj_id = project_mgr.check_and_create_proj(self._scan_path)
  File "F:\Users\Administrator\Desktop\工作内容\716\CHM\client\node\localtask\projectmgr.py", line 163, in check_and_create_proj
    self._repo_id = self.__check_and_create_repo(format_repo_url)
  File "F:\Users\Administrator\Desktop\工作内容\716\CHM\client\node\localtask\projectmgr.py", line 84, in __check_and_create_repo
    is_existed, repo_id = self._dog_server.is_repo_existed(repo_url, self._org_sid, self._team_name)
  File "util\wrapper.py", line 28, in util.wrapper.__c__.__c__.__call__

这是我的配置信息
![image](https://user-images.githubusercontent.com/49626869/218710893-835448d8-9352-448c-8413-5a9de3d4ce4f.png)

![image](https://user-images.githubusercontent.com/49626869/218710839-9f7fa8d3-b1dc-48f7-b9df-1c186a4db375.png)

**Comment by 33yan** [comment]
我测试的时候也遇到这个问题，后面排查发现是用前端生成的codedog.ini配置，里面的codedog_env字段的配置最后缺失斜杆/，导致拼接的api地址不对，自己加个/在main后面就可以了，如codedog_env : http://192.168.31.10/server/main/

**Comment by 980468094** [comment]
谢谢，确实是这样，已经解决了
