### ISSUE TITLE
windows下使用客户端二进制启动分析，tscan工具报错

### ISSUE THREAD

**Issue by Gandhizx** [Tencent/CodeAnalysis#803]
代码是C#和lua，分析方案中添加了tscan相关规则就报错。去掉的话分析能正常进行。

错误日志：
2023-03-22 10:56:36,193-INFO: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
2023-03-22 10:56:36,193-INFO: Codelint only scans main code.
2023-03-22 10:56:36,217-WARNING: task status code is 201
2023-03-22 10:56:36,217-WARNING: task messsage: TypeError: expected str, bytes or os.PathLike object, not NoneType
2023-03-22 10:56:36,217-WARNING: task result: 
Traceback (most recent call last):
  File "task\puppytask.py", line 63, in run
  File "task\runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "task\taskmgr.py", line 73, in taskrunner
  File "task\model\analyze.py", line 49, in runner
  File "tool\tscan_csharp.py", line 30, in analyze
  File "tool\util\tscan.py", line 50, in analyze
  File "ntpath.py", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by auula** [comment]
> 代码是C#和lua，分析方案中添加了tscan相关规则就报错。去掉的话分析能正常进行。
> 
> 错误日志： 2023-03-22 10:56:36,193-INFO: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source). 2023-03-22 10:56:36,193-INFO: Codelint only scans main code. 2023-03-22 10:56:36,217-WARNING: task status code is 201 2023-03-22 10:56:36,217-WARNING: task messsage: TypeError: expected str, bytes or os.PathLike object, not NoneType 2023-03-22 10:56:36,217-WARNING: task result: Traceback (most recent call last): File "task\puppytask.py", line 63, in run File "task\runtask.py", line 129, in task.runtask.**tskr**.**tskr**.run_task File "task\taskmgr.py", line 73, in taskrunner File "task\model\analyze.py", line 49, in runner File "tool\tscan_csharp.py", line 30, in analyze File "tool\util\tscan.py", line 50, in analyze File "ntpath.py", line 76, in join TypeError: expected str, bytes or os.PathLike object, not NoneType

是不是相关规则填写错误。

**Comment by auula** [comment]
看看官方文档，是否格式和规则编写正确。

**Comment by auula** [comment]
看样子是 数据类型错误 :

>TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by didebughu** [comment]
看上去是文件路径或文件名异常导致的，可以过滤掉含有特殊字符命名的文件试试
