### ISSUE TITLE
程序安装在program files目录下，报权限错误！

### ISSUE THREAD

**Issue by brucehsie** [Tencent/CodeAnalysis#846]
2023-06-06 20:14:40,828-INFO: running in a PyInstaller bundle
2023-06-06 20:14:41,082-WARNING: env TCA_QUICK_SCAN_INPUT not exists, scan the source dir.
2023-06-06 20:14:41,101-INFO: [文件数]过滤前：431，过滤后：431
[13420] Failed to execute script 'codepuppy' due to unhandled exception!
Traceback (most recent call last):
  File "node\quicktask\quickrunner.py", line 381, in run
  File "node\quicktask\quickrunner.py", line 316, in _generate_request
  File "node\common\taskdirmgr.py", line 51, in acquire_task_dir
  File "os.py", line 223, in makedirs
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Program Files (x86)\\CHMClient\\bin\\data\\taskdirs\\task_13'

**Comment by cyw3** [comment]
有几个问题想了解下：

1. TCA是什么部署方式呢？
2. TCA Client是使用什么启动方式呢？是自行接入的节点，还是localscan的方式呢？
3. TCA Client是下载的windows的版本吗？
4. 是否尝试给TCA Client赋予权限呢？

**Comment by brucehsie** [comment]
TCA client 是直接下载的windows版本, 采用了quickscan方式， 给codepuppy.exe赋予了管理员权限，也一样。

**Comment by cyw3** [comment]
> TCA client 是直接下载的windows版本, 采用了quickscan方式， 给codepuppy.exe赋予了管理员权限，也一样。

麻烦给客户端目录下的其他exe后缀文件也赋予管理员权限试试
