### ISSUE TITLE
执行分析时，文件名称包含“,” 时，会报文件找不到错误

### ISSUE THREAD

**Issue by ningjunwei** [Tencent/CodeAnalysis#914]
![5Jf4DjVpgZ](https://github.com/Tencent/CodeAnalysis/assets/79590928/44aaa8e5-17e5-405c-b952-8db030f19429)

文件名称：ambalink_sdk_4_9/linux/include/dt-bindings/clock/qcom,gcc-apq8084.h
关键Log如下：
2023-09-07 14:53:39,606-INFO: 代码库总行数是: 26601476
2023-09-07 14:53:39,606-INFO: 开始重复代码扫描...
2023-09-07 14:53:40,065-ERROR: 过滤路径(['*\\.java', '.*ambalink_sdk_4_9/linux/include/dt-bindings/reset/amlogic*', '.*\\.java', '.*ambalink_sdk_4_9/linux/include/dt-bindings/reset/amlogic.*', '.*/ambalink_sdk_4_9/linux/include/dt-bindings/.*', '.*/\\.svn/.*', '\\.svn/.*', '.*/\\.git/.*', '\\.git/.*', '.*/pinpoint_piggy/.*', '.*/\\.git', '.*/thirdparty/.*', 'thirdparty/.*', '.*/google\\.golang\\.org/.*', '.*/externlibs/.*', 'externlibs/.*', 'lua/jit/.*', '.*/lua/jit/.*', '.*/third/.*', 'third/.*', '.*/.*\\.dll', '.*/gopkg\\.in/.*', 'gopkg\\.in/.*', '.*/tdrbuf/.*', 'tdrbuf/.*', '.*/third_party/.*', 'third_party/.*', '.*/tools/.*', 'tools/.*', '.*/third-party/.*', 'third-party/.*', '.*/3rd/.*', '3rd/.*', '.*/highcharts.*.js', '.*/pbprotocol/.*', 'pbprotocol/.*', '.*/boost/.*', 'boost/.*', '.*/jquery.*\\.js', '.*/tinyxml/.*', 'tinyxml/.*', '.*/.*\\.exe', '.*/lib_3rd/.*', 'lib_3rd/.*', '.*/github\\.com/.*', '.*/node_modules/.*', 'node_modules/.*', '.*/3rdParty/.*', '3rdParty/.*', '.*/tinyxml2/.*', 'tinyxml2/.*', '.*/universaldetector\\.py', '.*/demo/.*', 'demo/.*', '.*/mobdebug\\.lua', '.*/external/.*', 'external/.*', '.*/ProgramFiles/.*', '.*/.*\\.pb\\.cc', '.*\\.min\\.js', '.*/tool/.*', 'tool/.*', '.*/3rdlib/.*', '3rdlib/.*', '.*/.*\\.svg', '.*/ProgramFiles\\(x86\\)/.*', '.*/luajit/jit/.*', '.*/protobuf/.*', 'protobuf/.*', '.*/extensions/.*', 'extensions/.*', '.*/Tdr/.*', 'Tdr/.*', '.*/ThirdPart/.*', 'ThirdPart/.*', '.*/lib/.*', 'lib/.*', '.*/echarts.*.js', '.*/gtest/.*', 'gtest/.*', '.*/curl/.*', 'curl/.*', '.*/lib3rd/.*', 'lib3rd/.*', '.*/\\.temp/.*', '.*/.*\\.tar', '.*/New3rdpartylib/.*', 'New3rdpartylib/.*', '.*/vendors/.*', 'vendors/.*', '.*/ThirdPartyCode/.*', 'ThirdPartyCode/.*', '.*/Plugins/.*', 'Plugins/.*', '.*/third_lib/.*', 'third_lib/.*', '.*/vue.*\\.js', '.*/golang\\.org/.*', '.*/TDRExported/.*', 'TDRExported/.*', '.*/.*\\.pb\\.cpp', '.*/.*\\.pb\\.h', 'pinpoint_piggy/.*', '.*/R\\.java', '.*/main\\.dart\\.js', '.*/vendor/.*', 'vendor/.*', '(?s:.*\\.java)\\Z', '(?s:.*ambalink_sdk_4_9/linux/include/dt\\-bindings/reset/amlogic.*)\\Z', '.*/ZendEngine/.*', 'ZendEngine/.*'])格式有误,将导致过滤不生效: nothing to repeat at position 0
2023-09-07 14:53:40,422-INFO: [文件数]过滤前：53228，过滤后：53228
2023-09-07 14:53:40,438-INFO: cmd: bin/run.sh cpd --minimum-tokens 120 --format csv_with_linecount_per_file --encoding utf-8 --ignore-literals --ignore-annotations --ignore-usings --skip-lexical-errors --failOnViolation false --language cpp --filelist /workspace/client/data/taskdirs/task_509/workdir/cpd_cpp_paths.txt
2023-09-07 14:53:41,300-INFO: java.lang.IllegalStateException: java.io.FileNotFoundException: Couldn't find directory/file '/workspace/src/ambalink_sdk_4_9/linux/include/dt-bindings/clock/qcom'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "src/subprocc.py", line 440, in src.subprocc.SubProcController.__run_stderr_proc__
  File "src/subprocc.py", line 428, in src.subprocc.SubProcController.__run_stderr_proc__
  File "src/subprocc.py", line 273, in src.subprocc.SubProcController.__call_stderr_line_callback__
  File "tool/cpd.py", line 202, in tool.cpd.__c__.__c__._error_handle
util.exceptions.AnalyzeTaskError: Error[211]: 请检查代码库或者扫描路径设置中对应目录下是否有对应语种的代码文件，比如选择Java语种的项目，对应目录下是否包含有.java文件。
2023-09-07 14:53:41,394-WARNING: task status code is 211
2023-09-07 14:53:41,395-WARNING: task messsage: AnalyzeTaskError: Error[211]: 请检查代码库或者扫描路径设置中对应目录下是否有对应语种的代码文件，比如选择Java语种的项目，对应目录下是否包含有.java文件。
2023-09-07 14:53:41,395-WARNING: task result: 
Traceback (most recent call last):
  File "task/puppytask.py", line 63, in run
    response = TaskRunner(self._request_file, self._response_file).run_task()
  File "task/runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "/workspace/client/task/taskmgr.py", line 73, in taskrunner
    result = task.runner(params)
  File "/workspace/client/task/model/analyze.py", line 49, in runner
    return self.tool.analyze(params)
  File "tool/cpd.py", line 133, in tool.cpd.__c__.__c__.analyze
  File "tool/cpd.py", line 192, in tool.cpd.__c__.__c__.__dupl_scan__
  File "src/subprocc.py", line 569, in src.subprocc.SubProcController.wait
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "src/subprocc.py", line 440, in src.subprocc.SubProcController.__run_stderr_proc__
  File "src/subprocc.py", line 428, in src.subprocc.SubProcController.__run_stderr_proc__
  File "src/subprocc.py", line 273, in src.subprocc.SubProcController.__call_stderr_line_callback__
  File "tool/cpd.py", line 202, in tool.cpd.__c__.__c__._error_handle
util.exceptions.AnalyzeTaskError: Error[211]: 请检查代码库或者扫描路径设置中对应目录下是否有对应语种的代码文件，比如选择Java语种的项目，对应目录下是否包含有.java文件。

**Comment by cyw3** [comment]
这边确认了下，确实CPD工具存在该问题。建议将该问题反馈给工具官方。

另外可以规范下文件方式可以避免这个问题。

**Comment by ningjunwei** [comment]
> 这边确认了下，确实CPD工具存在该问题。建议将该问题反馈给工具官方。
> 
> 另外可以规范下文件方式可以避免这个问题。

好的，我先把相关的文件做个过滤
