### ISSUE TITLE
license-classifier工具扫描目标文件数为0时，会执行异常，应该返回空结果

### ISSUE THREAD

**Issue by aaaa-j** [Tencent/CodeAnalysis#947]
2023-11-09 12:15:21,663-INFO: finish getting scm diff filepaths
2023-11-09 12:15:21,673-INFO: [文件数]过滤前：1，过滤后：0
2023-11-09 12:15:21,712-INFO: -- start run tool ...
2023-11-09 12:15:21,712-INFO: [debug] source_dir: /workspace/src
2023-11-09 12:15:21,712-INFO: [debug] get diff file: /workspace/client/data/taskdirs/task_4757/diff_files.json
2023-11-09 12:15:21,712-INFO: [error] To-be-scanned files is empty
2023-11-09 12:15:21,712-INFO: -- end ...
2023-11-09 12:15:21,774-INFO: use SubProcController run cmd: python main.py
2023-11-09 12:15:21,776-WARNING: task status code is 226
2023-11-09 12:15:21,776-WARNING: task messsage: TaskError: Error[226]: 第三方工具(license-classifier)执行异常,未生成结果文件result.json
2023-11-09 12:15:21,777-WARNING: task result: 
Traceback (most recent call last):
  File "task/puppytask.py", line 63, in run
    response = TaskRunner(self._request_file, self._response_file).run_task()
  File "task/runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "/workspace/client/task/taskmgr.py", line 73, in taskrunner
    result = task.runner(params)
  File "/workspace/client/task/model/analyze.py", line 49, in runner
    return self.tool.analyze(params)
  File "tool/customtool.py", line 319, in tool.customtool.__c__.__c__.analyze
util.exceptions.TaskError: Error[226]: 第三方工具(license-classifier)执行异常,未生成结果文件result.json

**Comment by yql70** [comment]
已修复，麻烦更新工具重试下
