### ISSUE TITLE
luacheck分析大项目的时候会因为文件太多导致命令参数过长

### ISSUE THREAD

**Issue by zl569808** [Tencent/CodeAnalysis#952]
2023-11-15 17:36:46,748-WARNING: task status code is 201
2023-11-15 17:36:46,748-WARNING: task messsage: OSError: [Errno 7] Argument list too long: '/bin/sh'
2023-11-15 17:36:46,756-WARNING: task result: 
Traceback (most recent call last):
  File "task/puppytask.py", line 63, in run
    response = TaskRunner(self._request_file, self._response_file).run_task()
  File "task/runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "/home/codeanalysis/client/task/taskmgr.py", line 73, in taskrunner
    result = task.runner(params)
  File "/home/codeanalysis/client/task/model/analyze.py", line 49, in runner
    return self.tool.analyze(params)
  File "/home/codeanalysis/client/tool/luacheck.py", line 105, in analyze
    SubProcController(scan_cmd, stdout_filepath=error_output, stderr_line_callback=self.print_log).wait()
  File "src/subprocc.py", line 569, in src.subprocc.SubProcController.wait
  File "src/subprocc.py", line 451, in src.subprocc.SubProcController.run
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/python3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: '/bin/sh'

**Comment by cyw3** [comment]
可以调整为逐文件分析。

欢迎PR

**Comment by cyw3** [comment]
已有大佬实现 👍
