### ISSUE TITLE
使用findbugs时，指令gradle未找到

### ISSUE THREAD

**Issue by nlhm** [Tencent/CodeAnalysis#978]
2024-01-02 13:09:16,945-INFO: start to run task: Findbugs, execute_processes: ['compile', 'analyze', 'datahandle']
2024-01-02 13:09:16,995-INFO: Load tool config: https://git.code.tencent.com/TCA/tca-tools/puppy-tools-config.git
2024-01-02 13:09:18,500-INFO: Initing common tools ...
2024-01-02 13:09:18,501-INFO: Initing 3 tools, please wait a minute ...

[Tools init]:   0%|                                                           | 0/3 [00:00<?, ?it/s]
[Tools init]:  33%|█████████████████                                  | 1/3 [00:01<00:03,  1.56s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.86it/s]
2024-01-02 13:09:20,122-INFO: Initialize tools done.(use time: 1.62s)
2024-01-02 13:09:20,124-INFO: run cmd: git lfs install
2024-01-02 13:09:20,204-INFO: Git LFS initialized.
2024-01-02 13:09:20,272-INFO: Initing other tools ...
2024-01-02 13:09:20,280-INFO: Initing 2 tools, please wait a minute ...

[Tools init]:   0%|                                                           | 0/2 [00:00<?, ?it/s]
[Tools init]:  50%|█████████████████████████▌                         | 1/2 [00:01<00:01,  1.62s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.20it/s]
2024-01-02 13:09:21,942-INFO: Initialize tools done.(use time: 1.66s)
2024-01-02 13:09:21,973-INFO: task start : <class 'task.model.compile.CompileTask'>
2024-01-02 13:09:21,973-INFO: pre_compile start.
2024-01-02 13:09:21,973-INFO: start __checkout_source_dir.
2024-01-02 13:09:21,973-INFO: 常规项目，直接拉取或复用本地缓存资源.
2024-01-02 13:09:23,780-INFO: load_source_dir done. source_dir insert env. sourcedir: /CodeAnalysis/client/data/sourcedirs/git_7usyx5_z
2024-01-02 13:09:23,788-INFO: pre_compile done.
2024-01-02 13:09:23,792-INFO: PATH =
****************************************************************************************************
/CodeAnalysis/tools/linux-jdk1.8.0_65/bin
/CodeAnalysis/tools/findbugs/bin
/CodeAnalysis/tools/linux-git-lfs-v3.1.2
/CodeAnalysis/tools/linux-git-lfs-v3.1.2
/usr/local/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/lib/jvm/java-8-openjdk-amd64/bin
**/opt/gradle-6.5/bin**
****************************************************************************************************
2024-01-02 13:09:23,794-INFO: Codemetric only scans main code (exclude test_source, auto_generate_source, third_party_source).
2024-01-02 13:09:23,794-INFO: Codelint only scans main code.
2024-01-02 13:09:23,861-INFO: task params taskdir: /CodeAnalysis/client/data/taskdirs/task_163
2024-01-02 13:09:23,866-INFO: Tool compile start.
2024-01-02 13:09:23,868-INFO: Cmd:
gradle compileDebugSources
2024-01-02 13:09:23,868-INFO: Generated shell file: /CodeAnalysis/client/data/taskdirs/task_163/workdir/tca_build.sh
2024-01-02 13:09:23,868-INFO: basic compile start.
2024-01-02 13:09:23,868-INFO: subprocc normal mode: ['bash', '/CodeAnalysis/client/data/taskdirs/task_163/workdir/tca_build.sh']
2024-01-02 13:09:23,868-INFO: run build cmd: bash /CodeAnalysis/client/data/taskdirs/task_163/workdir/tca_build.sh
2024-01-02 13:09:23,878-INFO: /CodeAnalysis/client/data/taskdirs/task_163/workdir/tca_build.sh: line 1: gradle: command not found
2024-01-02 13:09:23,938-INFO: [文件数]过滤前：1462，过滤后：1187
2024-01-02 13:09:23,938-INFO: ['/CodeAnalysis/tools/linux-scc/scc', '--by-file', '-c', '--no-cocomo', '-f', 'json', '-o', '/CodeAnalysis/client/data/taskdirs/task_163/scc_result_182e8086a92d11ee8ecb0242ac110002.json', '/CodeAnalysis/client/data/sourcedirs/git_7usyx5_z']
2024-01-02 13:09:23,970-INFO: exist_error_flag : True
2024-01-02 13:09:23,970-INFO: exist_success_flag : False
2024-01-02 13:09:23,970-INFO: exist_100_flag : False
2024-01-02 13:09:23,970-INFO: cov_no_file_emitted : False
2024-01-02 13:09:23,970-INFO: 编译结束，rc为：127
2024-01-02 13:09:23,973-WARNING: task status code is 210
2024-01-02 13:09:23,973-WARNING: task messsage: CompileTaskError: Error[210]: 项目编译失败，请确认当前版本是否能在本地进行编译！
2024-01-02 13:09:23,980-WARNING: task result: 
Traceback (most recent call last):
  File "task/puppytask.py", line 63, in run
    response = TaskRunner(self._request_file, self._response_file).run_task()
  File "task/runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "/CodeAnalysis/client/task/taskmgr.py", line 73, in taskrunner
    result = task.runner(params)
  File "/CodeAnalysis/client/task/model/compile.py", line 49, in runner
    return self.tool.compile(params)
  File "/CodeAnalysis/client/tool/findbugs.py", line 101, in compile
    build_cmd=BasicCompile.generate_shell_file(build_cmd)).compile()
  File "/CodeAnalysis/client/tool/util/compile.py", line 163, in compile
    self.handle_log(spc.returncode)
  File "/CodeAnalysis/client/tool/util/compile.py", line 203, in handle_log
    raise CompileTaskError(msg="项目编译失败，请确认当前版本是否能在本地进行编译！")
util.exceptions.CompileTaskError: Error[210]: 项目编译失败，请确认当前版本是否能在本地进行编译！

 ---

GRADLE_HOME=/opt/gradle-6.5
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
PATH=$PATH:$JAVA_HOME/bin:$GRADLE_HOME/bin
我在分析方案中的环境变量已经配置gradle路径，不知道为什么还是提示命令未找到。

TCA部署在Ubuntu中，在Ubuntu终端中已经使用gradle命令编译通过该工程。

**Comment by cyw3** [comment]
有几个问题：
1. 使用的执行节点是官方默认的节点吗？还是自己接入的节点？
2. 如果使用官方的节点，对应的 GRADLE_HOME=/opt/gradle-6.5 位置有在官方节点机器中安装吗？
建议接入自己的节点，这样方便管理机器环境

**Comment by nlhm** [comment]
你好，感谢回复。

1. 是官方默认的节点.
2. 对应的 GRADLE_HOME=/opt/gradle-6.5 位置安装在官方节点机器。

---

此外，我自己又部署了一台Windows节点的机器，将gradle加入系统path中，而且在分析方案中也配置环境变量，这个节点是能够编译成功的。
不过在使用javawarning时提示下面的错误信息。
![image](https://github.com/Tencent/CodeAnalysis/assets/46469364/2e171dfb-2e61-40e4-9326-b318e4c6dd6a)

错误日志见下：

2024-01-02 18:55:34,327-INFO: start to run task: AndroidLint, execute_processes: ['compile', 'analyze', 'datahandle']
2024-01-02 18:55:34,535-INFO: Load tool config: https://git.code.tencent.com/TCA/tca-tools/puppy-tools-config.git
2024-01-02 18:55:40,347-INFO: Initing common tools ...
2024-01-02 18:55:40,347-INFO: Initing 3 tools, please wait a minute ...

[Tools init]:   0%|                                                           | 0/3 [00:00<?, ?it/s]
[Tools init]:  33%|█████████████████                                  | 1/3 [00:07<00:14,  7.18s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 3/3 [00:07<00:00,  2.40s/it]
2024-01-02 18:55:47,542-INFO: Initialize tools done.(use time: 7.19s)
2024-01-02 18:55:47,543-INFO: run cmd: git lfs install
2024-01-02 18:55:48,576-INFO: Git LFS initialized.
2024-01-02 18:55:48,668-INFO: Initing other tools ...
2024-01-02 18:55:48,673-INFO: Initing 2 tools, please wait a minute ...

[Tools init]:   0%|                                                           | 0/2 [00:00<?, ?it/s]
[Tools init]:  50%|█████████████████████████▌                         | 1/2 [00:05<00:05,  5.78s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.45s/it]
[Tools init]: 100%|███████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.95s/it]
2024-01-02 18:55:54,582-INFO: Initialize tools done.(use time: 5.91s)
2024-01-02 18:55:54,582-INFO: task start : <class 'task.model.compile.CompileTask'>
2024-01-02 18:55:54,582-INFO: pre_compile start.
2024-01-02 18:55:54,582-INFO: start __checkout_source_dir.
2024-01-02 18:55:54,582-INFO: 常规项目，直接拉取或复用本地缓存资源.
2024-01-02 18:55:59,941-INFO: load_source_dir done. source_dir insert env. sourcedir: C:\Users\huimi\Desktop\TCA\CodeAnalysis\client\data\sourcedirs\git_j33qqk5c
2024-01-02 18:55:59,941-INFO: pre_compile done.
2024-01-02 18:55:59,941-INFO: PATH =
****************************************************************************************************
C:\Users\huimi\Desktop\TCA\CodeAnalysis\tools\win-jdk1.8.0_91/bin
C:\Users\huimi\Desktop\TCA\CodeAnalysis\tools\win-git-lfs-v3.1.2
C:\Users\huimi\Desktop\TCA\CodeAnalysis\tools\win-git-lfs-v3.1.2
……
省略
……
2024-01-02 17:22:57,326-INFO: 
2024-01-02 17:22:57,326-INFO: BUILD SUCCESSFUL in 2m 56s
2024-01-02 17:22:57,326-INFO: 101 actionable tasks: 15 executed, 86 up-to-date
2024-01-02 17:22:57,799-INFO: exist_error_flag : False
2024-01-02 17:22:57,799-INFO: exist_success_flag : True
2024-01-02 17:22:57,799-INFO: exist_100_flag : False
2024-01-02 17:22:57,799-INFO: cov_no_file_emitted : False
2024-01-02 17:22:57,799-INFO: 编译成功！
2024-01-02 17:22:57,799-INFO: basic compile done.
2024-01-02 17:22:57,799-INFO: done_compile start.
2024-01-02 17:22:57,799-INFO: task done : <class 'task.model.compile.CompileTask'>
2024-01-02 17:22:57,811-INFO: task start : <class 'task.model.analyze.AnalyzeTask'>
2024-01-02 17:22:57,811-INFO: pre_analyze start.
2024-01-02 17:22:57,811-INFO: pre_analyze done.
2024-01-02 17:22:57,884-WARNING: task status code is 201
2024-01-02 17:22:57,884-WARNING: task messsage: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 1726: invalid continuation byte
2024-01-02 17:22:57,887-WARNING: task result: 
Traceback (most recent call last):
  File "task\puppytask.py", line 63, in run
  File "task\runtask.py", line 129, in task.runtask.__tskr__.__tskr__.run_task
  File "task\taskmgr.py", line 73, in taskrunner
  File "task\model\analyze.py", line 49, in runner
  File "tool\javawarning.py", line 68, in analyze
  File "d:\app\python37\lib\codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 1726: invalid continuation byte

2024-01-02 17:22:57,888-INFO: task result: \路径……\CodeAnalysis\client\data\taskdirs\task_320\task_response.json

---

我有些疑惑Ubuntu的节点为何不能编译成功，以及在Windows节点下的问题该如何解决？是我配置的问题还是工程本身的问题？

**Comment by cyw3** [comment]
1. Ubuntu的节点为何不能编译成功?
这个目前由于缺乏足够信息无法判断，可以自行尝试登录节点调试下，看任务执行时候gradle是否存在。

2. Windows节点下的问题该如何解决？
这里应该是编码问题，可以尝试 基于 [htmlcs中读取文件的代码](https://github.com/Tencent/CodeAnalysis/blob/47ac6f0bbea47c3cb55e492d78751310f2bc62cb/client/tool/htmlcs.py#L92) 调试 [javawarning读取文件位置代码](https://github.com/Tencent/CodeAnalysis/blob/47ac6f0bbea47c3cb55e492d78751310f2bc62cb/client/tool/javawarning.py#L67) 试试
